import { BadRequestException, ConflictException, Injectable, NotFoundException, OnModuleDestroy } from '@nestjs/common';
import { PrismaClient } from '@simoes/database';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { reverse } from 'node:dns/promises';
import * as net from 'node:net';
import { Queue } from 'bullmq';
import { AuditService } from '../audit/audit.service';
import { AuthenticatedUser } from '../auth/auth.service';
import { CreateDiscoveryJobDto, CreateHostDto, CreateIpDto, CreateServiceDto, CreateSiteDto, CreateSubnetDto, CreateVlanDto, ReviewDiscoveryResultDto, UpdateDiscoveryScheduleDto, UpdateHostDto, UpdateIpDto, UpdateServiceDto, UpdateSiteDto, UpdateSubnetDto, UpdateVlanDto } from './dto';
import { IpamAccessService } from './ipam-access.service';
import { assertDiscoveryAllowed, DiscoveryPolicyError, normalizeDiscoveryPorts, parseNetwork } from '../discovery/discovery-policy';

const execFileAsync = promisify(execFile);
const MAX_DISCOVERY_HOSTS = 4096;

function ipv4ToNumber(ip: string) { return ip.split('.').reduce((value, part) => (value * 256) + Number(part), 0) >>> 0; }
function numberToIpv4(value: number) { return [value >>> 24, (value >>> 16) & 255, (value >>> 8) & 255, value & 255].join('.'); }
function parseCidr(cidr: string) {
  const [address, bitsText] = cidr.trim().split('/');
  const bits = Number(bitsText);
  if (!/^\d{1,3}(\.\d{1,3}){3}$/.test(address) || !Number.isInteger(bits) || bits < 0 || bits > 32 || address.split('.').some((part) => Number(part) > 255)) throw new BadRequestException('A subnet deve ser um CIDR IPv4 válido');
  const mask = bits === 0 ? 0 : (0xffffffff << (32 - bits)) >>> 0;
  const network = ipv4ToNumber(address) & mask;
  return { bits, network, broadcast: (network | (~mask >>> 0)) >>> 0 };
}
function assertAddressInSubnet(address: string, cidr: string) {
  if (!/^\d{1,3}(\.\d{1,3}){3}$/.test(address)) throw new BadRequestException('A Fase 4 suporta inicialmente endereços IPv4');
  const parsed = parseCidr(cidr); const value = ipv4ToNumber(address);
  if (value < parsed.network || value > parsed.broadcast) throw new BadRequestException('O IP não pertence à subnet indicada');
}
function usableHosts(cidr: string) {
  const parsed = parseCidr(cidr);
  const first = parsed.bits >= 31 ? parsed.network : parsed.network + 1;
  const last = parsed.bits >= 31 ? parsed.broadcast : parsed.broadcast - 1;
  const count = last >= first ? last - first + 1 : 0;
  if (count > MAX_DISCOVERY_HOSTS) throw new BadRequestException(`A descoberta está limitada a ${MAX_DISCOVERY_HOSTS} hosts por execução`);
  return Array.from({ length: count }, (_, index) => numberToIpv4(first + index));
}

@Injectable()
export class IpamService implements OnModuleDestroy {
  private readonly discoveryQueue = new Queue('discovery', { connection: this.redisConnection() });
  constructor(private readonly prisma: PrismaClient, private readonly audit: AuditService, private readonly access: IpamAccessService) {}
  async onModuleDestroy() { await this.discoveryQueue.disconnect(); }
  private redisConnection() { const url = new URL(process.env.REDIS_URL ?? 'redis://localhost:6379'); return { host: url.hostname, port: Number(url.port || 6379), ...(url.password ? { password: url.password } : {}) }; }
  private async auditChange(user: AuthenticatedUser, action: string, entityType: string, entityId: string, metadata?: unknown) { await this.audit.record({ userId: user.id, action, entityType, entityId, metadata }); }

  async listSites(user: AuthenticatedUser, search?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100); const accessWhere = await this.access.whereFor(user, 'READ', 'site'); const searchWhere = search ? { OR: [{ name: { contains: search, mode: 'insensitive' as const } }, { code: { contains: search, mode: 'insensitive' as const } }, { city: { contains: search, mode: 'insensitive' as const } }] } : {}; const where = { AND: [accessWhere, searchWhere] }; const [items, total] = await Promise.all([this.prisma.site.findMany({ where, include: { _count: { select: { buildings: true, vlans: true, subnets: true } } }, orderBy: { name: 'asc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.site.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async networkMap(user: AuthenticatedUser, siteId: string) {
    await this.access.assertSite(user, 'READ', siteId);
    const [vlanAccess, subnetAccess] = await Promise.all([this.access.whereFor(user, 'READ', 'vlan'), this.access.whereFor(user, 'READ', 'subnet')]);
    const site = await this.prisma.site.findUnique({ where: { id: siteId }, select: { id: true, name: true, code: true, city: true } });
    if (!site) throw new NotFoundException('Site não encontrado');
    const vlans = await this.prisma.vlan.findMany({
      where: { AND: [{ siteId }, vlanAccess] }, orderBy: { vlanId: 'asc' },
      include: {
        subnets: { where: subnetAccess, include: { _count: { select: { ips: true } } }, orderBy: { cidr: 'asc' } },
        nativeInterfaces: { include: { device: { include: { model: { select: { manufacturer: true, model: true } } } } } },
        accessInterfaces: { include: { device: { include: { model: { select: { manufacturer: true, model: true } } } } } },
        interfaceVlans: { include: { interface: { include: { device: { include: { model: { select: { manufacturer: true, model: true } } } } } } } },
      },
    });
    return { site, vlans: vlans.map((vlan) => {
      const interfaces = [...vlan.nativeInterfaces.map((item) => ({ ...item, relation: 'native' })), ...vlan.accessInterfaces.map((item) => ({ ...item, relation: 'access' })), ...vlan.interfaceVlans.map((item) => ({ ...item.interface, relation: item.tagged ? 'allowed' : 'access' }))];
      const uniqueInterfaces = Array.from(new Map(interfaces.map((item) => [item.id, item])).values());
      const devices = Array.from(new Map(uniqueInterfaces.map((item) => [item.device.id, item.device])).values()).map((device) => ({ id: device.id, name: device.name, type: device.type, status: device.status, hostname: device.hostname, model: device.model, interfaces: uniqueInterfaces.filter((item) => item.deviceId === device.id).map((item) => ({ id: item.id, name: item.name, mode: item.mode, relation: item.relation, adminUp: item.adminUp, operUp: item.operUp })) }));
      const subnet = vlan.subnets[0] ?? null;
      const status = !subnet ? 'MISSING_SUBNET' : devices.length === 0 ? 'NO_EQUIPMENT' : 'CONFIGURED';
      return { id: vlan.id, vlanId: vlan.vlanId, name: vlan.name, description: vlan.description, subnet: subnet ? { id: subnet.id, cidr: subnet.cidr, gateway: subnet.gateway, purpose: subnet.purpose, ipCount: subnet._count.ips } : null, devices, interfaces: uniqueInterfaces.map((item) => ({ id: item.id, name: item.name, deviceId: item.deviceId, deviceName: item.device.name, mode: item.mode, relation: item.relation, adminUp: item.adminUp, operUp: item.operUp })), status };
    }) };
  }
  async createSite(dto: CreateSiteDto, user: AuthenticatedUser) { await this.access.assertContext(user, 'CREATE', {}); try { const site = await this.prisma.site.create({ data: { ...dto, code: dto.code.trim().toUpperCase() } }); await this.auditChange(user, 'SITE_CREATED', 'Site', site.id, { name: site.name, code: site.code }); return site; } catch { throw new ConflictException('Já existe um site com esse código'); } }
  async updateSite(id: string, dto: UpdateSiteDto, user: AuthenticatedUser) { await this.access.assertSite(user, 'UPDATE', id); const site = await this.prisma.site.update({ where: { id }, data: { ...dto, code: dto.code.trim().toUpperCase() } }).catch(() => { throw new NotFoundException('Site não encontrado'); }); await this.auditChange(user, 'SITE_UPDATED', 'Site', id); return site; }
  async deleteSite(id: string, user: AuthenticatedUser) { await this.access.assertSite(user, 'DELETE', id); const site = await this.prisma.site.findUnique({ where: { id }, include: { _count: { select: { buildings: true, devices: true, vlans: true, subnets: true } } } }); if (!site) throw new NotFoundException('Site não encontrado'); const dependencies = site._count; if (Object.values(dependencies).some((count) => count > 0)) throw new ConflictException({ code: 'SITE_NOT_EMPTY', message: 'Só é possível eliminar Sites vazios.', dependencies }); await this.prisma.site.delete({ where: { id } }); await this.auditChange(user, 'SITE_DELETED', 'Site', id, { name: site.name, code: site.code }); return { success: true }; }

  async listVlans(user: AuthenticatedUser, siteId?: string, search?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100); const accessWhere = await this.access.whereFor(user, 'READ', 'vlan'); const filters = { ...(siteId ? { siteId } : {}), ...(search ? { OR: [{ name: { contains: search, mode: 'insensitive' as const } }, { description: { contains: search, mode: 'insensitive' as const } }] } : {}) }; const where = { AND: [accessWhere, filters] }; const [items, total] = await Promise.all([this.prisma.vlan.findMany({ where, include: { site: true, _count: { select: { subnets: true } } }, orderBy: [{ vlanId: 'asc' }], skip: (page - 1) * pageSize, take: pageSize }), this.prisma.vlan.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async createVlan(dto: CreateVlanDto, user: AuthenticatedUser) { if (dto.siteId) await this.access.assertSite(user, 'CREATE', dto.siteId); try { const vlan = await this.prisma.vlan.create({ data: { vlanId: dto.vlanId, name: dto.name, description: dto.description, siteId: dto.siteId || null } }); await this.auditChange(user, 'VLAN_CREATED', 'Vlan', vlan.id, { vlanId: vlan.vlanId }); return vlan; } catch { throw new ConflictException('Já existe essa VLAN no site indicado'); } }
  async updateVlan(id: string, dto: UpdateVlanDto, user: AuthenticatedUser) { const current = await this.access.assertVlan(user, 'UPDATE', id); if (dto.siteId && dto.siteId !== current.siteId) await this.access.assertSite(user, 'UPDATE', dto.siteId); const vlan = await this.prisma.vlan.update({ where: { id }, data: { vlanId: dto.vlanId, name: dto.name, description: dto.description, siteId: dto.siteId || null } }).catch(() => { throw new NotFoundException('VLAN não encontrada'); }); await this.auditChange(user, 'VLAN_UPDATED', 'Vlan', id); return vlan; }
  async deleteVlan(id: string, user: AuthenticatedUser) { await this.access.assertVlan(user, 'DELETE', id); const vlan = await this.prisma.vlan.findUnique({ where: { id }, include: { _count: { select: { subnets: true, nativeInterfaces: true, accessInterfaces: true, interfaceVlans: true } } } }); if (!vlan) throw new NotFoundException('VLAN não encontrada'); const linked = vlan._count.subnets + vlan._count.nativeInterfaces + vlan._count.accessInterfaces + vlan._count.interfaceVlans; if (linked) throw new ConflictException(`Não é possível eliminar esta VLAN: existem ${linked} relações de subnet/interface associadas.`); await this.prisma.vlan.delete({ where: { id } }); await this.auditChange(user, 'VLAN_DELETED', 'Vlan', id, { vlanId: vlan.vlanId }); return { success: true }; }

  async listSubnets(user: AuthenticatedUser, siteId?: string, vlanId?: string, search?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100); const accessWhere = await this.access.whereFor(user, 'READ', 'subnet'); const filters = { ...(siteId ? { siteId } : {}), ...(vlanId ? { vlanId } : {}), ...(search ? { OR: [{ cidr: { contains: search, mode: 'insensitive' as const } }, { purpose: { contains: search, mode: 'insensitive' as const } }, { environment: { contains: search, mode: 'insensitive' as const } }] } : {}) }; const where = { AND: [accessWhere, filters] }; const [items, total] = await Promise.all([this.prisma.subnet.findMany({ where, include: { site: true, vlan: true, _count: { select: { ips: true, discoveryJobs: true } } }, orderBy: { cidr: 'asc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.subnet.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async createSubnet(dto: CreateSubnetDto, user: AuthenticatedUser) { const parsed = parseCidr(dto.cidr); const cidr = `${numberToIpv4(parsed.network)}/${parsed.bits}`; if (dto.vlanId && await this.prisma.subnet.findFirst({ where: { vlanId: dto.vlanId } })) throw new ConflictException('A VLAN já tem uma subnet associada'); try { const subnet = await this.prisma.subnet.create({ data: { cidr, version: 4, gateway: dto.gateway, purpose: dto.purpose, environment: dto.environment, siteId: dto.siteId || null, vlanId: dto.vlanId || null } }); await this.auditChange(user, 'SUBNET_CREATED', 'Subnet', subnet.id, { cidr }); return subnet; } catch { throw new ConflictException('Já existe essa subnet ou a VLAN já está associada'); } }
  async deleteSubnet(id: string, user: AuthenticatedUser) { await this.access.assertSubnet(user, 'DELETE', id); const subnet = await this.prisma.subnet.findUnique({ where: { id } }); if (!subnet) throw new NotFoundException('Subnet não encontrada'); await this.prisma.subnet.delete({ where: { id } }); await this.auditChange(user, 'SUBNET_DELETED', 'Subnet', id, { cidr: subnet.cidr }); return { success: true }; }

  async listIps(user: AuthenticatedUser, subnetId?: string, state?: string, source?: string, search?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 50, 1), 200); const accessWhere = await this.access.whereFor(user, 'READ', 'ip'); const filters = { ...(subnetId ? { subnetId } : {}), ...(state ? { state: state as never } : {}), ...(source ? { source: source as never } : {}), ...(search ? { OR: [{ address: { contains: search } }, { hostname: { contains: search, mode: 'insensitive' as const } }, { macAddress: { contains: search, mode: 'insensitive' as const } }] } : {}) }; const where = { AND: [accessWhere, filters] }; const [items, total] = await Promise.all([this.prisma.ipAddress.findMany({ where, include: { subnet: { include: { vlan: true } }, device: true, interface: { include: { device: true } }, host: { include: { _count: { select: { services: true } } } } }, orderBy: { address: 'asc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.ipAddress.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async createIp(dto: CreateIpDto, user: AuthenticatedUser) { const subnet = await this.access.assertSubnet(user, 'CREATE', dto.subnetId); if (dto.hostId) await this.access.assertHost(user, 'UPDATE', dto.hostId); const fullSubnet = await this.prisma.subnet.findUniqueOrThrow({ where: { id: subnet.id } }); assertAddressInSubnet(dto.address, fullSubnet.cidr); try { const ip = await this.prisma.ipAddress.create({ data: { address: dto.address, subnetId: dto.subnetId, state: (dto.state ?? 'UNKNOWN') as never, hostname: dto.hostname, macAddress: dto.macAddress, notes: dto.notes, source: 'MANUAL', hostId: dto.hostId, deviceId: dto.deviceId, interfaceId: dto.interfaceId } }); await this.auditChange(user, 'IP_ADDRESS_CREATED', 'IpAddress', ip.id, { address: ip.address }); return ip; } catch { throw new ConflictException({ code: 'IP_CONFLICT', message: 'Esse IP já existe na subnet ou contém relações inválidas.' }); } }
  async updateIp(id: string, dto: UpdateIpDto, user: AuthenticatedUser) { const authorized = await this.access.assertIp(user, 'UPDATE', id); const current = await this.prisma.ipAddress.findUnique({ where: { id }, include: { subnet: true } }); if (!current) throw new NotFoundException('IP não encontrado'); if (dto.hostId && dto.hostId !== current.hostId) await this.access.assertHost(user, 'UPDATE', dto.hostId); if (current.hostId && dto.hostId !== undefined && dto.hostId !== current.hostId) await this.access.assertHost(user, 'UPDATE', current.hostId); if (dto.address) assertAddressInSubnet(dto.address, current.subnet.cidr); const ip = await this.prisma.ipAddress.update({ where: { id }, data: { address: dto.address, state: dto.state as never, hostname: dto.hostname, macAddress: dto.macAddress, notes: dto.notes, hostId: dto.hostId, deviceId: dto.deviceId, interfaceId: dto.interfaceId } }).catch(() => { throw new ConflictException('O novo IP já existe ou não é válido'); }); await this.auditChange(user, 'IP_ADDRESS_UPDATED', 'IpAddress', id, { address: ip.address, state: ip.state, subnetId: authorized.subnetId }); return ip; }
  async deleteIp(id: string, user: AuthenticatedUser) { const ip = await this.access.assertIp(user, 'DELETE', id); await this.prisma.ipAddress.delete({ where: { id } }); await this.auditChange(user, 'IP_ADDRESS_DELETED', 'IpAddress', id, { address: ip.address }); return { success: true }; }

  async listHosts(user: AuthenticatedUser, siteId?: string, vlanId?: string, subnetId?: string, state?: string, source?: string, search?: string, pageText?: string, pageSizeText?: string) {
    const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100);
    const accessWhere = await this.access.whereFor(user, 'READ', 'host');
    const filters = { ...(state ? { status: state as never } : {}), ...(source ? { source: source as never } : {}), ...((siteId || vlanId || subnetId) ? { ipAddresses: { some: { subnet: { ...(siteId ? { siteId } : {}), ...(vlanId ? { vlanId } : {}), ...(subnetId ? { id: subnetId } : {}) } } } } : {}), ...(search ? { OR: [{ name: { contains: search, mode: 'insensitive' as const } }, { hostname: { contains: search, mode: 'insensitive' as const } }, { observedHostname: { contains: search, mode: 'insensitive' as const } }, { operatingSystem: { contains: search, mode: 'insensitive' as const } }, { macAddress: { contains: search, mode: 'insensitive' as const } }] } : {}) };
    const where = { AND: [accessWhere, filters] };
    const [items, total] = await Promise.all([this.prisma.host.findMany({ where, include: { ipAddresses: { select: { id: true, address: true, state: true, observedState: true, subnet: { select: { id: true, cidr: true, vlan: true } } } }, device: { select: { id: true, name: true, type: true } }, _count: { select: { services: true } } }, orderBy: { name: 'asc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.host.count({ where })]);
    return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) };
  }
  async getHost(user: AuthenticatedUser, id: string) { await this.access.assertHost(user, 'READ', id); const host = await this.prisma.host.findUnique({ where: { id }, include: { device: { include: { model: true, rack: { include: { room: { include: { building: true } } } } } }, ipAddresses: { include: { subnet: { include: { site: true, vlan: true, vrf: true } }, interface: { include: { device: true } }, device: true } }, services: { orderBy: [{ port: 'asc' }, { name: 'asc' }] } } }); if (!host) throw new NotFoundException({ code: 'HOST_NOT_FOUND', message: 'Host não encontrado.' }); return host; }
  async createHost(dto: CreateHostDto, user: AuthenticatedUser) {
    if (dto.ipAddressId) await this.access.assertIp(user, 'UPDATE', dto.ipAddressId); else await this.access.assertContext(user, 'CREATE', {});
    const { ipAddressId, ...data } = dto;
    if (data.deviceId && await this.prisma.host.findFirst({ where: { deviceId: data.deviceId } })) throw new ConflictException({ code: 'DEVICE_HOST_CONFLICT', message: 'O equipamento já está associado a outro Host.' });
    try { const host = await this.prisma.$transaction(async (tx) => { const created = await tx.host.create({ data: { ...data, status: (data.status ?? 'UNKNOWN') as never, source: 'MANUAL' } }); if (ipAddressId) await tx.ipAddress.update({ where: { id: ipAddressId }, data: { hostId: created.id } }); return created; }); await this.auditChange(user, 'HOST_CREATED', 'Host', host.id, { name: host.name, ipAddressId }); return this.getHost(user, host.id); } catch (error) { if (error instanceof ConflictException) throw error; throw new ConflictException({ code: 'HOST_CONFLICT', message: 'Já existe um Host com esse nome ou equipamento.' }); }
  }
  async updateHost(id: string, dto: UpdateHostDto, user: AuthenticatedUser) { await this.access.assertHost(user, 'UPDATE', id); const host = await this.prisma.host.update({ where: { id }, data: { ...dto, status: dto.status as never } }).catch(() => { throw new ConflictException({ code: 'HOST_UPDATE_CONFLICT', message: 'Não foi possível atualizar o Host; confirma o nome e o equipamento associado.' }); }); await this.auditChange(user, 'HOST_UPDATED', 'Host', id, { fields: Object.keys(dto) }); return this.getHost(user, host.id); }
  async retireHost(id: string, user: AuthenticatedUser) { const host = await this.access.assertHost(user, 'DELETE', id); await this.prisma.host.update({ where: { id }, data: { status: 'RETIRED' } }); await this.auditChange(user, 'HOST_RETIRED', 'Host', id, { name: host.name }); return { success: true }; }
  async linkHostIp(hostId: string, ipId: string, user: AuthenticatedUser) { await this.access.assertHost(user, 'UPDATE', hostId); const current = await this.access.assertIp(user, 'UPDATE', ipId); if (current.hostId && current.hostId !== hostId) await this.access.assertHost(user, 'UPDATE', current.hostId); const ip = await this.prisma.ipAddress.update({ where: { id: ipId }, data: { hostId } }); await this.auditChange(user, 'HOST_IP_LINKED', 'Host', hostId, { ipId, previousHostId: current.hostId }); return ip; }
  async unlinkHostIp(hostId: string, ipId: string, user: AuthenticatedUser) { await this.access.assertHost(user, 'UPDATE', hostId); const ip = await this.access.assertIp(user, 'UPDATE', ipId); if (ip.hostId !== hostId) throw new NotFoundException({ code: 'HOST_IP_LINK_NOT_FOUND', message: 'A associação Host/IP não existe.' }); const updated = await this.prisma.ipAddress.update({ where: { id: ipId }, data: { hostId: null } }); await this.auditChange(user, 'HOST_IP_UNLINKED', 'Host', hostId, { ipId }); return updated; }
  async linkHostDevice(hostId: string, deviceId: string, user: AuthenticatedUser) { await this.access.assertHost(user, 'UPDATE', hostId); const device = await this.prisma.device.findUnique({ where: { id: deviceId }, include: { host: true } }); if (!device) throw new NotFoundException({ code: 'DEVICE_NOT_FOUND', message: 'Equipamento não encontrado.' }); if (device.host && device.host.id !== hostId) throw new ConflictException({ code: 'DEVICE_HOST_CONFLICT', message: 'O equipamento já está associado a outro Host.' }); await this.prisma.host.update({ where: { id: hostId }, data: { deviceId } }); await this.auditChange(user, 'HOST_DEVICE_LINKED', 'Host', hostId, { deviceId }); return this.getHost(user, hostId); }
  async unlinkHostDevice(hostId: string, user: AuthenticatedUser) { const host = await this.access.assertHost(user, 'UPDATE', hostId); await this.prisma.host.update({ where: { id: hostId }, data: { deviceId: null } }); await this.auditChange(user, 'HOST_DEVICE_UNLINKED', 'Host', hostId, { deviceId: host.deviceId }); return this.getHost(user, hostId); }
  async listServices(user: AuthenticatedUser, hostId: string) { await this.access.assertHost(user, 'READ', hostId); return this.prisma.service.findMany({ where: { hostId }, orderBy: [{ port: 'asc' }, { name: 'asc' }] }); }
  private validateService(protocol?: string | null, port?: number | null) { if ((protocol === 'TCP' || protocol === 'UDP') && !port) throw new BadRequestException({ code: 'SERVICE_PORT_REQUIRED', message: 'Services TCP/UDP exigem uma porta.' }); }
  async createService(dto: CreateServiceDto, user: AuthenticatedUser) { await this.access.assertHost(user, 'UPDATE', dto.hostId); this.validateService(dto.protocol, dto.port); try { const service = await this.prisma.service.create({ data: { ...dto, protocol: dto.protocol?.toUpperCase(), source: 'MANUAL' } }); await this.auditChange(user, 'SERVICE_CREATED', 'Service', service.id, { name: service.name, hostId: dto.hostId }); return service; } catch (error) { if (error instanceof BadRequestException) throw error; throw new ConflictException({ code: 'SERVICE_CONFLICT', message: 'Já existe esse Service no Host.' }); } }
  async updateService(id: string, dto: UpdateServiceDto, user: AuthenticatedUser) { const current = await this.prisma.service.findUnique({ where: { id } }); if (!current) throw new NotFoundException({ code: 'SERVICE_NOT_FOUND', message: 'Service não encontrado.' }); await this.access.assertHost(user, 'UPDATE', current.hostId); const protocol = dto.protocol ?? current.protocol; const port = dto.port ?? current.port; this.validateService(protocol, port); const updated = await this.prisma.service.update({ where: { id }, data: { ...dto, protocol: dto.protocol?.toUpperCase() } }); await this.auditChange(user, 'SERVICE_UPDATED', 'Service', id, { hostId: current.hostId }); return updated; }
  async deleteService(id: string, user: AuthenticatedUser) { const current = await this.prisma.service.findUnique({ where: { id } }); if (!current) throw new NotFoundException({ code: 'SERVICE_NOT_FOUND', message: 'Service não encontrado.' }); await this.access.assertHost(user, 'DELETE', current.hostId); await this.prisma.service.delete({ where: { id } }); await this.auditChange(user, 'SERVICE_DELETED', 'Service', id, { hostId: current.hostId, name: current.name }); return { success: true }; }

  async discoverySummary(user: AuthenticatedUser) { try { const subnetWhere = await this.access.whereFor(user, 'READ', 'subnet'); const [counts, pendingResults, worker] = await Promise.all([this.discoveryQueue.getJobCounts('waiting', 'active', 'completed', 'failed'), this.prisma.discoveryResult.count({ where: { status: 'PENDING', job: { subnet: subnetWhere } } }), this.discoveryQueue.getJobCounts('waiting', 'active').then(() => 'operational').catch(() => 'unavailable')]); return { worker, pendingResults, queue: counts }; } catch { return { worker: 'unavailable', pendingResults: 0, queue: {} }; } }
  async listDiscoveryJobs(user: AuthenticatedUser, status?: string, subnetId?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100); const subnetWhere = await this.access.whereFor(user, 'READ', 'subnet'); const where = { ...(status ? { status: status as never } : {}), ...(subnetId ? { subnetId } : {}), subnet: subnetWhere }; const [items, total] = await Promise.all([this.prisma.discoveryJob.findMany({ where, include: { subnet: { include: { vlan: true, site: true } }, _count: { select: { results: true } } }, orderBy: { createdAt: 'desc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.discoveryJob.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async getDiscoveryJob(user: AuthenticatedUser, id: string) { const job = await this.prisma.discoveryJob.findUnique({ where: { id }, include: { subnet: { include: { vlan: true, site: true } }, _count: { select: { results: true } } } }); if (!job) throw new NotFoundException('Execução de discovery não encontrada'); await this.access.assertSubnet(user, 'READ', job.subnetId); return job; }
  async listDiscoveryResults(user: AuthenticatedUser, jobId: string) { await this.getDiscoveryJob(user, jobId); return this.prisma.discoveryResult.findMany({ where: { jobId }, orderBy: [{ status: 'asc' }, { address: 'asc' }] }); }
  async runDiscovery(dto: CreateDiscoveryJobDto, user: AuthenticatedUser) { const [subnet, settings] = await Promise.all([this.access.assertSubnet(user, 'DISCOVER', dto.subnetId), this.prisma.systemSettings.findFirst()]); const fullSubnet = await this.prisma.subnet.findUniqueOrThrow({ where: { id: subnet.id } }); const methods = [...new Set(dto.methods)].filter((method) => method === 'ICMP' || method === 'TCP'); let tcpPorts: number[]; try { tcpPorts = normalizeDiscoveryPorts(dto.tcpPorts ?? []); const target = assertDiscoveryAllowed(fullSubnet.cidr, settings?.discoveryAllowedCidrs); if (target.version !== 4) throw new DiscoveryPolicyError('DISCOVERY_IPV6_UNSUPPORTED', 'A enumeração de subnets IPv6 ainda não é suportada.'); } catch (error) { if (error instanceof DiscoveryPolicyError) throw new BadRequestException({ code: error.code, message: error.message }); throw error; } const reverseDns = dto.reverseDns ?? settings?.discoveryDefaultReverseDns ?? true; if (!methods.length) throw new BadRequestException({ code: 'DISCOVERY_METHOD_REQUIRED', message: 'Escolhe pelo menos um método.' }); if (methods.includes('TCP') && !tcpPorts.length) throw new BadRequestException({ code: 'TCP_PORT_REQUIRED', message: 'Define pelo menos uma porta para Discovery TCP.' }); try { const job = await this.prisma.discoveryJob.create({ data: { name: dto.name, subnetId: dto.subnetId, methods, tcpPorts, reverseDns } }); await this.discoveryQueue.add('scan-subnet', { jobId: job.id }, { jobId: job.id, removeOnComplete: 100, removeOnFail: 100 }); await this.auditChange(user, 'DISCOVERY_QUEUED', 'DiscoveryJob', job.id, { methods, subnet: fullSubnet.cidr, reverseDns }); return job; } catch { throw new ConflictException({ code: 'DISCOVERY_ALREADY_ACTIVE', message: 'Já existe uma execução ativa para esta subnet.' }); } }

  async getDiscoverySchedule(user: AuthenticatedUser, subnetId: string) { await this.access.assertSubnet(user, 'READ', subnetId); const [existing, settings] = await Promise.all([this.prisma.discoverySchedule.findUnique({ where: { subnetId } }), this.prisma.systemSettings.findFirst()]); return existing ?? { subnetId, enabled: false, intervalHours: settings?.discoveryDefaultIntervalHours ?? 12, methods: settings?.discoveryDefaultMethods ?? ['ICMP', 'TCP'], tcpPorts: settings?.discoveryDefaultTcpPorts ?? [22, 80, 443, 3389], reverseDns: settings?.discoveryDefaultReverseDns ?? true, lastRunAt: null, nextRunAt: null, lastStatus: null, lastError: null }; }
  async updateDiscoverySchedule(subnetId: string, dto: UpdateDiscoveryScheduleDto, user: AuthenticatedUser) { const [subnet, defaults] = await Promise.all([this.access.assertSubnet(user, 'DISCOVER', subnetId), this.prisma.systemSettings.findFirst()]); const fullSubnet = await this.prisma.subnet.findUniqueOrThrow({ where: { id: subnet.id } }); const methods = [...new Set(dto.methods)].filter((method) => method === 'ICMP' || method === 'TCP'); let tcpPorts: number[]; try { tcpPorts = normalizeDiscoveryPorts(dto.tcpPorts ?? []); const target = assertDiscoveryAllowed(fullSubnet.cidr, defaults?.discoveryAllowedCidrs); if (target.version !== 4) throw new DiscoveryPolicyError('DISCOVERY_IPV6_UNSUPPORTED', 'A enumeração de subnets IPv6 ainda não é suportada.'); } catch (error) { if (error instanceof DiscoveryPolicyError) throw new BadRequestException({ code: error.code, message: error.message }); throw error; } if (!methods.length) throw new BadRequestException('Escolhe pelo menos um método'); if (methods.includes('TCP') && !tcpPorts.length) throw new BadRequestException('Define pelo menos uma porta TCP'); const intervalHours = dto.intervalHours ?? defaults?.discoveryDefaultIntervalHours ?? 12; const reverseDns = dto.reverseDns ?? defaults?.discoveryDefaultReverseDns ?? true; const every = intervalHours * 60 * 60 * 1000; const nextRunAt = dto.enabled ? new Date(Date.now() + every) : null; const schedule = await this.prisma.discoverySchedule.upsert({ where: { subnetId }, create: { subnetId, enabled: dto.enabled, intervalHours, methods, tcpPorts, reverseDns, nextRunAt }, update: { enabled: dto.enabled, intervalHours, methods, tcpPorts, reverseDns, nextRunAt, lastError: null } }); if (dto.enabled) await this.discoveryQueue.upsertJobScheduler(`subnet-${subnetId}`, { every }, { name: 'scheduled-subnet-scan', data: { subnetId } }); else await this.discoveryQueue.removeJobScheduler(`subnet-${subnetId}`); await this.auditChange(user, 'DISCOVERY_SCHEDULE_UPDATED', 'DiscoverySchedule', schedule.id, { subnetId, enabled: dto.enabled, intervalHours, reverseDns }); return schedule; }
  async runScheduledDiscovery(subnetId: string, user: AuthenticatedUser) { const schedule = await this.prisma.discoverySchedule.findUnique({ where: { subnetId } }); if (!schedule || !schedule.enabled) throw new ConflictException('O auto-discovery está desligado para esta subnet'); const methods = Array.isArray(schedule.methods) ? schedule.methods.filter((value): value is string => typeof value === 'string') : ['ICMP']; const tcpPorts = Array.isArray(schedule.tcpPorts) ? schedule.tcpPorts.filter((value): value is number => typeof value === 'number') : []; const job = await this.runDiscovery({ name: `Discovery agendado · ${new Date().toISOString()}`, subnetId, methods, tcpPorts, reverseDns: schedule.reverseDns }, user); await this.prisma.discoverySchedule.update({ where: { subnetId }, data: { lastRunAt: new Date(), nextRunAt: new Date(Date.now() + schedule.intervalHours * 60 * 60 * 1000), lastStatus: 'QUEUED' } }); return job; }

  private async executeDiscovery(jobId: string, cidr: string, methods: string[], tcpPorts: number[]) {
    try {
      await this.prisma.discoveryJob.update({ where: { id: jobId }, data: { status: 'RUNNING', startedAt: new Date() } });
      const addresses = usableHosts(cidr); const results: { jobId: string; address: string; hostname?: string; icmpReachable: boolean; responseMs?: number; openPorts: number[] }[] = [];
      for (let index = 0; index < addresses.length; index += 32) {
        const batch = addresses.slice(index, index + 32);
        results.push(...await Promise.all(batch.map(async (address) => {
          const icmp = methods.includes('ICMP') ? await this.ping(address) : { reachable: false, responseMs: undefined };
          const openPorts = methods.includes('TCP') ? (await Promise.all(tcpPorts.map(async (port) => (await this.testPort(address, port)) ? port : null))).filter((port): port is number => port !== null) : [];
          let hostname: string | undefined; try { hostname = (await reverse(address))[0]; } catch { /* reverse DNS is best effort */ }
          return { jobId, address, hostname, icmpReachable: icmp.reachable, responseMs: icmp.responseMs, openPorts };
        })));
      }
      if (results.length) await this.prisma.discoveryResult.createMany({ data: results.map((result) => ({ ...result, openPorts: result.openPorts })) });
      await this.prisma.discoveryJob.update({ where: { id: jobId }, data: { status: 'COMPLETED', completedAt: new Date() } });
    } catch (error) { await this.prisma.discoveryJob.update({ where: { id: jobId }, data: { status: 'FAILED', completedAt: new Date(), errorMessage: error instanceof Error ? error.message : 'Erro desconhecido' } }); }
  }
  private async ping(address: string) { const started = Date.now(); try { const args = process.platform === 'win32' ? ['-n', '1', '-w', '800', address] : ['-c', '1', '-W', '1', address]; await execFileAsync(process.platform === 'win32' ? 'ping.exe' : 'ping', args, { timeout: 1500, windowsHide: true }); return { reachable: true, responseMs: Date.now() - started }; } catch { return { reachable: false, responseMs: undefined }; } }
  private testPort(address: string, port: number) { return new Promise<boolean>((resolve) => { const socket = net.createConnection({ host: address, port, timeout: 800 }); const done = (result: boolean) => { socket.destroy(); resolve(result); }; socket.once('connect', () => done(true)); socket.once('timeout', () => done(false)); socket.once('error', () => done(false)); }); }

  async reviewResult(id: string, dto: ReviewDiscoveryResultDto, user: AuthenticatedUser) {
    const result = await this.prisma.discoveryResult.findUnique({ where: { id }, include: { job: true } });
    if (!result) throw new NotFoundException({ code: 'DISCOVERY_RESULT_NOT_FOUND', message: 'Resultado não encontrado.' });
    await this.access.assertSubnet(user, 'DISCOVER', result.job.subnetId);
    const now = new Date(); const source = result.icmpReachable ? 'ICMP' : 'TCP';
    const reviewed = await this.prisma.$transaction(async (tx) => {
      const claimed = await tx.discoveryResult.updateMany({ where: { id, status: 'PENDING' }, data: { status: dto.status as never, reviewedAt: now, reviewedBy: user.id } });
      if (!claimed.count) { const current = await tx.discoveryResult.findUniqueOrThrow({ where: { id } }); if (current.status === dto.status) return { result: current, changed: false }; throw new ConflictException({ code: 'DISCOVERY_RESULT_ALREADY_REVIEWED', message: 'O resultado já foi revisto.' }); }
      const updatedResult = await tx.discoveryResult.findUniqueOrThrow({ where: { id } });
      if (dto.status !== 'APPROVED') return { result: updatedResult, changed: true };
      const existingIp = await tx.ipAddress.findUnique({ where: { subnetId_address: { subnetId: result.job.subnetId, address: result.address } }, include: { host: true } });
      let host = existingIp?.host;
      if (!host) {
        const baseName = result.hostname || result.address;
        const collision = await tx.host.findUnique({ where: { name: baseName } });
        const contextualName = `${baseName} (${result.address})`; const contextualCollision = collision ? await tx.host.findUnique({ where: { name: contextualName } }) : null;
        const name = !collision ? baseName : contextualCollision ? `${contextualName} #${result.id.slice(0, 8)}` : contextualName;
        host = await tx.host.create({ data: { name, source, observedHostname: result.hostname, observedStatus: 'REACHABLE', status: 'UNKNOWN', lastSeenAt: now } });
      } else {
        host = await tx.host.update({ where: { id: host.id }, data: { observedHostname: result.hostname, observedStatus: 'REACHABLE', lastSeenAt: now } });
      }
      if (existingIp) await tx.ipAddress.update({ where: { id: existingIp.id }, data: { hostId: host.id, observedState: 'REACHABLE', lastSeenAt: now, lastCheckAt: now, lastCheckMethod: source, icmpReachable: result.icmpReachable, responseMs: result.responseMs, openPorts: result.openPorts ?? [] } });
      else await tx.ipAddress.create({ data: { address: result.address, subnetId: result.job.subnetId, hostId: host.id, state: 'UNKNOWN', source, observedState: 'REACHABLE', lastSeenAt: now, lastCheckAt: now, lastCheckMethod: source, icmpReachable: result.icmpReachable, responseMs: result.responseMs, openPorts: result.openPorts ?? [] } });
      if (Array.isArray(result.openPorts)) for (const port of result.openPorts.filter((value): value is number => typeof value === 'number')) await tx.service.upsert({ where: { hostId_protocol_port: { hostId: host.id, protocol: 'TCP', port } }, create: { hostId: host.id, name: `TCP/${port}`, protocol: 'TCP', port, source: 'TCP', observedStatus: 'OPEN', lastSeenAt: now }, update: { observedStatus: 'OPEN', lastSeenAt: now } });
      return { result: updatedResult, changed: true };
    });
    if (reviewed.changed) await this.auditChange(user, `DISCOVERY_RESULT_${dto.status}`, 'DiscoveryResult', id, { address: result.address });
    return reviewed.result;
  }
}
