import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaClient } from '@simoes/database';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { reverse } from 'node:dns/promises';
import * as net from 'node:net';
import { Queue } from 'bullmq';
import { AuditService } from '../audit/audit.service';
import { AuthenticatedUser } from '../auth/auth.service';
import { CreateDiscoveryJobDto, CreateHostDto, CreateIpDto, CreateServiceDto, CreateSiteDto, CreateSubnetDto, CreateVlanDto, ReviewDiscoveryResultDto, UpdateDiscoveryScheduleDto, UpdateHostDto, UpdateIpDto, UpdateSiteDto, UpdateSubnetDto, UpdateVlanDto } from './dto';

const execFileAsync = promisify(execFile);
const MAX_DISCOVERY_HOSTS = 4096;

function ipv4ToNumber(ip: string) { return ip.split('.').reduce((value, part) => (value * 256) + Number(part), 0) >>> 0; }
function numberToIpv4(value: number) { return [value >>> 24, (value >>> 16) & 255, (value >>> 8) & 255, value & 255].join('.'); }
function parseCidr(cidr: string) {
  const [address, bitsText] = cidr.trim().split('/');
  const bits = Number(bitsText);
  if (!/^\d{1,3}(\.\d{1,3}){3}$/.test(address) || !Number.isInteger(bits) || bits < 0 || bits > 32 || address.split('.').some((part) => Number(part) > 255)) throw new BadRequestException('A subnet deve ser um CIDR IPv4 válido');
  const mask = bits === 0 ? 0 : (0xffffffff << (32 - bits)) >>> 0;
  const network = ipv4ToNumber(address) & mask;
  return { bits, network, broadcast: (network | (~mask >>> 0)) >>> 0 };
}
function assertAddressInSubnet(address: string, cidr: string) {
  if (!/^\d{1,3}(\.\d{1,3}){3}$/.test(address)) throw new BadRequestException('A Fase 4 suporta inicialmente endereços IPv4');
  const parsed = parseCidr(cidr); const value = ipv4ToNumber(address);
  if (value < parsed.network || value > parsed.broadcast) throw new BadRequestException('O IP não pertence à subnet indicada');
}
function usableHosts(cidr: string) {
  const parsed = parseCidr(cidr);
  const first = parsed.bits >= 31 ? parsed.network : parsed.network + 1;
  const last = parsed.bits >= 31 ? parsed.broadcast : parsed.broadcast - 1;
  const count = last >= first ? last - first + 1 : 0;
  if (count > MAX_DISCOVERY_HOSTS) throw new BadRequestException(`A descoberta está limitada a ${MAX_DISCOVERY_HOSTS} hosts por execução`);
  return Array.from({ length: count }, (_, index) => numberToIpv4(first + index));
}

@Injectable()
export class IpamService {
  private readonly discoveryQueue = new Queue('discovery', { connection: this.redisConnection() });
  constructor(private readonly prisma: PrismaClient, private readonly audit: AuditService) {}
  private redisConnection() { const url = new URL(process.env.REDIS_URL ?? 'redis://localhost:6379'); return { host: url.hostname, port: Number(url.port || 6379), ...(url.password ? { password: url.password } : {}) }; }
  private async auditChange(user: AuthenticatedUser, action: string, entityType: string, entityId: string, metadata?: unknown) { await this.audit.record({ userId: user.id, action, entityType, entityId, metadata }); }

  async listSites(search?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100); const where = search ? { OR: [{ name: { contains: search, mode: 'insensitive' as const } }, { code: { contains: search, mode: 'insensitive' as const } }, { city: { contains: search, mode: 'insensitive' as const } }] } : {}; const [items, total] = await Promise.all([this.prisma.site.findMany({ where, include: { _count: { select: { buildings: true, vlans: true, subnets: true } } }, orderBy: { name: 'asc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.site.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async networkMap(siteId: string) {
    const site = await this.prisma.site.findUnique({ where: { id: siteId }, select: { id: true, name: true, code: true, city: true } });
    if (!site) throw new NotFoundException('Site não encontrado');
    const vlans = await this.prisma.vlan.findMany({
      where: { siteId }, orderBy: { vlanId: 'asc' },
      include: {
        subnets: { include: { _count: { select: { ips: true } } }, orderBy: { cidr: 'asc' } },
        nativeInterfaces: { include: { device: { include: { model: { select: { manufacturer: true, model: true } } } } } },
        accessInterfaces: { include: { device: { include: { model: { select: { manufacturer: true, model: true } } } } } },
        interfaceVlans: { include: { interface: { include: { device: { include: { model: { select: { manufacturer: true, model: true } } } } } } } },
      },
    });
    return { site, vlans: vlans.map((vlan) => {
      const interfaces = [...vlan.nativeInterfaces.map((item) => ({ ...item, relation: 'native' })), ...vlan.accessInterfaces.map((item) => ({ ...item, relation: 'access' })), ...vlan.interfaceVlans.map((item) => ({ ...item.interface, relation: item.tagged ? 'allowed' : 'access' }))];
      const uniqueInterfaces = Array.from(new Map(interfaces.map((item) => [item.id, item])).values());
      const devices = Array.from(new Map(uniqueInterfaces.map((item) => [item.device.id, item.device])).values()).map((device) => ({ id: device.id, name: device.name, type: device.type, status: device.status, hostname: device.hostname, model: device.model, interfaces: uniqueInterfaces.filter((item) => item.deviceId === device.id).map((item) => ({ id: item.id, name: item.name, mode: item.mode, relation: item.relation, adminUp: item.adminUp, operUp: item.operUp })) }));
      const subnet = vlan.subnets[0] ?? null;
      const status = !subnet ? 'MISSING_SUBNET' : devices.length === 0 ? 'NO_EQUIPMENT' : 'CONFIGURED';
      return { id: vlan.id, vlanId: vlan.vlanId, name: vlan.name, description: vlan.description, subnet: subnet ? { id: subnet.id, cidr: subnet.cidr, gateway: subnet.gateway, purpose: subnet.purpose, ipCount: subnet._count.ips } : null, devices, interfaces: uniqueInterfaces.map((item) => ({ id: item.id, name: item.name, deviceId: item.deviceId, deviceName: item.device.name, mode: item.mode, relation: item.relation, adminUp: item.adminUp, operUp: item.operUp })), status };
    }) };
  }
  async createSite(dto: CreateSiteDto, user: AuthenticatedUser) { try { const site = await this.prisma.site.create({ data: { ...dto, code: dto.code.trim().toUpperCase() } }); await this.auditChange(user, 'SITE_CREATED', 'Site', site.id, { name: site.name, code: site.code }); return site; } catch { throw new ConflictException('Já existe um site com esse código'); } }
  async updateSite(id: string, dto: UpdateSiteDto, user: AuthenticatedUser) { const site = await this.prisma.site.update({ where: { id }, data: { ...dto, code: dto.code.trim().toUpperCase() } }).catch(() => { throw new NotFoundException('Site não encontrado'); }); await this.auditChange(user, 'SITE_UPDATED', 'Site', id); return site; }
  async deleteSite(id: string, user: AuthenticatedUser) { const site = await this.prisma.site.findUnique({ where: { id } }); if (!site) throw new NotFoundException('Site não encontrado'); await this.prisma.site.delete({ where: { id } }); await this.auditChange(user, 'SITE_DELETED', 'Site', id, { name: site.name, code: site.code }); return { success: true }; }

  async listVlans(siteId?: string, search?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100); const where = { ...(siteId ? { siteId } : {}), ...(search ? { OR: [{ name: { contains: search, mode: 'insensitive' as const } }, { description: { contains: search, mode: 'insensitive' as const } }] } : {}) }; const [items, total] = await Promise.all([this.prisma.vlan.findMany({ where, include: { site: true, _count: { select: { subnets: true } } }, orderBy: [{ vlanId: 'asc' }], skip: (page - 1) * pageSize, take: pageSize }), this.prisma.vlan.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async createVlan(dto: CreateVlanDto, user: AuthenticatedUser) { try { const vlan = await this.prisma.vlan.create({ data: { vlanId: dto.vlanId, name: dto.name, description: dto.description, siteId: dto.siteId || null } }); await this.auditChange(user, 'VLAN_CREATED', 'Vlan', vlan.id, { vlanId: vlan.vlanId }); return vlan; } catch { throw new ConflictException('Já existe essa VLAN no site indicado'); } }
  async updateVlan(id: string, dto: UpdateVlanDto, user: AuthenticatedUser) { const vlan = await this.prisma.vlan.update({ where: { id }, data: { vlanId: dto.vlanId, name: dto.name, description: dto.description, siteId: dto.siteId || null } }).catch(() => { throw new NotFoundException('VLAN não encontrada'); }); await this.auditChange(user, 'VLAN_UPDATED', 'Vlan', id); return vlan; }
  async deleteVlan(id: string, user: AuthenticatedUser) { const vlan = await this.prisma.vlan.findUnique({ where: { id }, include: { _count: { select: { subnets: true, nativeInterfaces: true, accessInterfaces: true, interfaceVlans: true } } } }); if (!vlan) throw new NotFoundException('VLAN não encontrada'); const linked = vlan._count.subnets + vlan._count.nativeInterfaces + vlan._count.accessInterfaces + vlan._count.interfaceVlans; if (linked) throw new ConflictException(`Não é possível eliminar esta VLAN: existem ${linked} relações de subnet/interface associadas.`); await this.prisma.vlan.delete({ where: { id } }); await this.auditChange(user, 'VLAN_DELETED', 'Vlan', id, { vlanId: vlan.vlanId }); return { success: true }; }

  async listSubnets(siteId?: string, vlanId?: string, search?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100); const where = { ...(siteId ? { siteId } : {}), ...(vlanId ? { vlanId } : {}), ...(search ? { OR: [{ cidr: { contains: search, mode: 'insensitive' as const } }, { purpose: { contains: search, mode: 'insensitive' as const } }, { environment: { contains: search, mode: 'insensitive' as const } }] } : {}) }; const [items, total] = await Promise.all([this.prisma.subnet.findMany({ where, include: { site: true, vlan: true, _count: { select: { ips: true, discoveryJobs: true } } }, orderBy: { cidr: 'asc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.subnet.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async createSubnet(dto: CreateSubnetDto, user: AuthenticatedUser) { const parsed = parseCidr(dto.cidr); const cidr = `${numberToIpv4(parsed.network)}/${parsed.bits}`; if (dto.vlanId && await this.prisma.subnet.findFirst({ where: { vlanId: dto.vlanId } })) throw new ConflictException('A VLAN já tem uma subnet associada'); try { const subnet = await this.prisma.subnet.create({ data: { cidr, version: 4, gateway: dto.gateway, purpose: dto.purpose, environment: dto.environment, siteId: dto.siteId || null, vlanId: dto.vlanId || null } }); await this.auditChange(user, 'SUBNET_CREATED', 'Subnet', subnet.id, { cidr }); return subnet; } catch { throw new ConflictException('Já existe essa subnet ou a VLAN já está associada'); } }
  async updateSubnet(id: string, dto: UpdateSubnetDto, user: AuthenticatedUser) { const parsed = parseCidr(dto.cidr); if (dto.vlanId && await this.prisma.subnet.findFirst({ where: { vlanId: dto.vlanId, NOT: { id } } })) throw new ConflictException('A VLAN já tem uma subnet associada'); const subnet = await this.prisma.subnet.update({ where: { id }, data: { cidr: `${numberToIpv4(parsed.network)}/${parsed.bits}`, version: 4, gateway: dto.gateway, purpose: dto.purpose, environment: dto.environment, siteId: dto.siteId || null, vlanId: dto.vlanId || null } }).catch(() => { throw new NotFoundException('Subnet não encontrada'); }); await this.auditChange(user, 'SUBNET_UPDATED', 'Subnet', id); return subnet; }
  async deleteSubnet(id: string, user: AuthenticatedUser) { const subnet = await this.prisma.subnet.findUnique({ where: { id } }); if (!subnet) throw new NotFoundException('Subnet não encontrada'); await this.prisma.subnet.delete({ where: { id } }); await this.auditChange(user, 'SUBNET_DELETED', 'Subnet', id, { cidr: subnet.cidr }); return { success: true }; }

  async listIps(subnetId?: string, state?: string, source?: string, search?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 50, 1), 200); const where = { ...(subnetId ? { subnetId } : {}), ...(state ? { state: state as never } : {}), ...(source ? { source: source as never } : {}), ...(search ? { OR: [{ address: { contains: search } }, { hostname: { contains: search, mode: 'insensitive' as const } }, { macAddress: { contains: search, mode: 'insensitive' as const } }] } : {}) }; const [items, total] = await Promise.all([this.prisma.ipAddress.findMany({ where, include: { subnet: { include: { vlan: true } }, device: true, host: { include: { _count: { select: { services: true } } } } }, orderBy: { address: 'asc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.ipAddress.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async createIp(dto: CreateIpDto, user: AuthenticatedUser) { const subnet = await this.prisma.subnet.findUnique({ where: { id: dto.subnetId } }); if (!subnet) throw new NotFoundException('Subnet não encontrada'); assertAddressInSubnet(dto.address, subnet.cidr); try { const ip = await this.prisma.ipAddress.create({ data: { address: dto.address, subnetId: dto.subnetId, state: (dto.state ?? 'UNKNOWN') as never, hostname: dto.hostname, macAddress: dto.macAddress, notes: dto.notes, source: 'MANUAL' } }); await this.auditChange(user, 'IP_ADDRESS_CREATED', 'IpAddress', ip.id, { address: ip.address }); return ip; } catch { throw new ConflictException('Esse IP já existe na subnet'); } }
  async updateIp(id: string, dto: UpdateIpDto, user: AuthenticatedUser) { const current = await this.prisma.ipAddress.findUnique({ where: { id }, include: { subnet: true } }); if (!current) throw new NotFoundException('IP não encontrado'); if (dto.address) assertAddressInSubnet(dto.address, current.subnet.cidr); const ip = await this.prisma.ipAddress.update({ where: { id }, data: { address: dto.address, state: dto.state as never, hostname: dto.hostname, macAddress: dto.macAddress, notes: dto.notes } }).catch(() => { throw new ConflictException('O novo IP já existe ou não é válido'); }); await this.auditChange(user, 'IP_ADDRESS_UPDATED', 'IpAddress', id, { address: ip.address, state: ip.state }); return ip; }
  async deleteIp(id: string, user: AuthenticatedUser) { const ip = await this.prisma.ipAddress.findUnique({ where: { id } }); if (!ip) throw new NotFoundException('IP não encontrado'); await this.prisma.ipAddress.delete({ where: { id } }); await this.auditChange(user, 'IP_ADDRESS_DELETED', 'IpAddress', id, { address: ip.address }); return { success: true }; }

  async listHosts(search?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100); const where = search ? { OR: [{ name: { contains: search, mode: 'insensitive' as const } }, { hostname: { contains: search, mode: 'insensitive' as const } }, { operatingSystem: { contains: search, mode: 'insensitive' as const } }] } : {}; const [items, total] = await Promise.all([this.prisma.host.findMany({ where, include: { ipAddresses: { select: { address: true, state: true } }, _count: { select: { services: true } } }, orderBy: { name: 'asc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.host.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async createHost(dto: CreateHostDto, user: AuthenticatedUser) { try { const host = await this.prisma.host.create({ data: dto }); await this.auditChange(user, 'HOST_CREATED', 'Host', host.id, { name: host.name }); return host; } catch { throw new ConflictException('Já existe um host com esse nome'); } }
  async updateHost(id: string, dto: UpdateHostDto, user: AuthenticatedUser) { const host = await this.prisma.host.update({ where: { id }, data: dto }).catch(() => { throw new NotFoundException('Host não encontrado'); }); await this.auditChange(user, 'HOST_UPDATED', 'Host', id); return host; }
  listServices(hostId: string) { return this.prisma.service.findMany({ where: { hostId }, orderBy: [{ port: 'asc' }, { name: 'asc' }] }); }
  async createService(dto: CreateServiceDto, user: AuthenticatedUser) { const host = await this.prisma.host.findUnique({ where: { id: dto.hostId } }); if (!host) throw new NotFoundException('Host não encontrado'); try { const service = await this.prisma.service.create({ data: dto }); await this.auditChange(user, 'SERVICE_CREATED', 'Service', service.id, { name: service.name, hostId: dto.hostId }); return service; } catch { throw new ConflictException('Já existe esse serviço no host'); } }

  async discoverySummary() { try { const [counts, pendingResults, worker] = await Promise.all([this.discoveryQueue.getJobCounts('waiting', 'active', 'completed', 'failed'), this.prisma.discoveryResult.count({ where: { status: 'PENDING' } }), this.discoveryQueue.getJobCounts('waiting', 'active').then(() => 'operational').catch(() => 'unavailable')]); return { worker, pendingResults, queue: counts }; } catch { return { worker: 'unavailable', pendingResults: 0, queue: {} }; } }
  async listDiscoveryJobs(status?: string, subnetId?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100); const where = { ...(status ? { status: status as never } : {}), ...(subnetId ? { subnetId } : {}) }; const [items, total] = await Promise.all([this.prisma.discoveryJob.findMany({ where, include: { subnet: { include: { vlan: true, site: true } }, _count: { select: { results: true } } }, orderBy: { createdAt: 'desc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.discoveryJob.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async getDiscoveryJob(id: string) { const job = await this.prisma.discoveryJob.findUnique({ where: { id }, include: { subnet: { include: { vlan: true, site: true } }, _count: { select: { results: true } } } }); if (!job) throw new NotFoundException('Execução de discovery não encontrada'); return job; }
  listDiscoveryResults(jobId: string) { return this.prisma.discoveryResult.findMany({ where: { jobId }, orderBy: [{ status: 'asc' }, { address: 'asc' }] }); }
  async runDiscovery(dto: CreateDiscoveryJobDto, user: AuthenticatedUser) { const subnet = await this.prisma.subnet.findUnique({ where: { id: dto.subnetId } }); if (!subnet) throw new NotFoundException('Subnet não encontrada'); const methods = [...new Set(dto.methods)]; const tcpPorts = [...new Set(dto.tcpPorts ?? [])]; if (!methods.length) throw new BadRequestException('Escolhe pelo menos um método'); if (methods.includes('TCP') && !tcpPorts.length) throw new BadRequestException('Define pelo menos uma porta para discovery TCP'); const job = await this.prisma.discoveryJob.create({ data: { name: dto.name, subnetId: dto.subnetId, methods, tcpPorts } }); await this.discoveryQueue.add('scan-subnet', { jobId: job.id, cidr: subnet.cidr, methods, tcpPorts }, { jobId: job.id, removeOnComplete: 100, removeOnFail: 100 }); await this.auditChange(user, 'DISCOVERY_QUEUED', 'DiscoveryJob', job.id, { methods, subnet: subnet.cidr }); return job; }

  async getDiscoverySchedule(subnetId: string) { const subnet = await this.prisma.subnet.findUnique({ where: { id: subnetId }, select: { id: true } }); if (!subnet) throw new NotFoundException('Subnet não encontrada'); return this.prisma.discoverySchedule.findUnique({ where: { subnetId } }) ?? { subnetId, enabled: false, intervalHours: 12, methods: ['ICMP'], tcpPorts: [22, 80, 443, 3389], lastRunAt: null, nextRunAt: null, lastStatus: null, lastError: null }; }
  async updateDiscoverySchedule(subnetId: string, dto: UpdateDiscoveryScheduleDto, user: AuthenticatedUser) { const subnet = await this.prisma.subnet.findUnique({ where: { id: subnetId } }); if (!subnet) throw new NotFoundException('Subnet não encontrada'); const methods = [...new Set(dto.methods)]; const tcpPorts = [...new Set(dto.tcpPorts ?? [])]; if (!methods.length) throw new BadRequestException('Escolhe pelo menos um método'); if (methods.includes('TCP') && !tcpPorts.length) throw new BadRequestException('Define pelo menos uma porta TCP'); const nextRunAt = dto.enabled ? new Date(Date.now() + 12 * 60 * 60 * 1000) : null; const schedule = await this.prisma.discoverySchedule.upsert({ where: { subnetId }, create: { subnetId, enabled: dto.enabled, intervalHours: 12, methods, tcpPorts, nextRunAt }, update: { enabled: dto.enabled, intervalHours: 12, methods, tcpPorts, nextRunAt, lastError: null } }); if (dto.enabled) await this.discoveryQueue.upsertJobScheduler(`subnet-${subnetId}`, { every: 12 * 60 * 60 * 1000 }, { name: 'scheduled-subnet-scan', data: { subnetId } }); else await this.discoveryQueue.removeJobScheduler(`subnet-${subnetId}`); await this.auditChange(user, 'DISCOVERY_SCHEDULE_UPDATED', 'DiscoverySchedule', schedule.id, { subnetId, enabled: dto.enabled }); return schedule; }
  async runScheduledDiscovery(subnetId: string, user: AuthenticatedUser) { const schedule = await this.prisma.discoverySchedule.findUnique({ where: { subnetId } }); if (!schedule || !schedule.enabled) throw new ConflictException('O auto-discovery está desligado para esta subnet'); const methods = Array.isArray(schedule.methods) ? schedule.methods.filter((value): value is string => typeof value === 'string') : ['ICMP']; const tcpPorts = Array.isArray(schedule.tcpPorts) ? schedule.tcpPorts.filter((value): value is number => typeof value === 'number') : []; const job = await this.runDiscovery({ name: `Discovery agendado · ${new Date().toISOString()}`, subnetId, methods, tcpPorts }, user); await this.prisma.discoverySchedule.update({ where: { subnetId }, data: { lastRunAt: new Date(), nextRunAt: new Date(Date.now() + 12 * 60 * 60 * 1000), lastStatus: 'QUEUED' } }); return job; }

  private async executeDiscovery(jobId: string, cidr: string, methods: string[], tcpPorts: number[]) {
    try {
      await this.prisma.discoveryJob.update({ where: { id: jobId }, data: { status: 'RUNNING', startedAt: new Date() } });
      const addresses = usableHosts(cidr); const results: { jobId: string; address: string; hostname?: string; icmpReachable: boolean; responseMs?: number; openPorts: number[] }[] = [];
      for (let index = 0; index < addresses.length; index += 32) {
        const batch = addresses.slice(index, index + 32);
        results.push(...await Promise.all(batch.map(async (address) => {
          const icmp = methods.includes('ICMP') ? await this.ping(address) : { reachable: false, responseMs: undefined };
          const openPorts = methods.includes('TCP') ? (await Promise.all(tcpPorts.map(async (port) => (await this.testPort(address, port)) ? port : null))).filter((port): port is number => port !== null) : [];
          let hostname: string | undefined; try { hostname = (await reverse(address))[0]; } catch { /* reverse DNS is best effort */ }
          return { jobId, address, hostname, icmpReachable: icmp.reachable, responseMs: icmp.responseMs, openPorts };
        })));
      }
      if (results.length) await this.prisma.discoveryResult.createMany({ data: results.map((result) => ({ ...result, openPorts: result.openPorts })) });
      await this.prisma.discoveryJob.update({ where: { id: jobId }, data: { status: 'COMPLETED', completedAt: new Date() } });
    } catch (error) { await this.prisma.discoveryJob.update({ where: { id: jobId }, data: { status: 'FAILED', completedAt: new Date(), errorMessage: error instanceof Error ? error.message : 'Erro desconhecido' } }); }
  }
  private async ping(address: string) { const started = Date.now(); try { const args = process.platform === 'win32' ? ['-n', '1', '-w', '800', address] : ['-c', '1', '-W', '1', address]; await execFileAsync(process.platform === 'win32' ? 'ping.exe' : 'ping', args, { timeout: 1500, windowsHide: true }); return { reachable: true, responseMs: Date.now() - started }; } catch { return { reachable: false, responseMs: undefined }; } }
  private testPort(address: string, port: number) { return new Promise<boolean>((resolve) => { const socket = net.createConnection({ host: address, port, timeout: 800 }); const done = (result: boolean) => { socket.destroy(); resolve(result); }; socket.once('connect', () => done(true)); socket.once('timeout', () => done(false)); socket.once('error', () => done(false)); }); }

  async reviewResult(id: string, dto: ReviewDiscoveryResultDto, user: AuthenticatedUser) { const result = await this.prisma.discoveryResult.findUnique({ where: { id }, include: { job: true } }); if (!result) throw new NotFoundException('Resultado não encontrado'); const reviewed = await this.prisma.discoveryResult.update({ where: { id }, data: { status: dto.status as never, reviewedAt: new Date(), reviewedBy: user.id } }); if (dto.status === 'APPROVED') { const hostName = result.hostname || result.address; const host = await this.prisma.host.upsert({ where: { name: hostName }, create: { name: hostName, hostname: result.hostname, status: 'ACTIVE', lastSeenAt: new Date() }, update: { hostname: result.hostname, status: 'ACTIVE', lastSeenAt: new Date() } }); await this.prisma.ipAddress.upsert({ where: { subnetId_address: { subnetId: result.job.subnetId, address: result.address } }, create: { address: result.address, subnetId: result.job.subnetId, hostId: host.id, hostname: result.hostname, state: 'OCCUPIED', source: result.icmpReachable ? 'ICMP' : 'TCP', lastSeenAt: new Date(), notes: result.openPorts ? `Portas TCP: ${JSON.stringify(result.openPorts)}` : undefined }, update: { hostId: host.id, hostname: result.hostname, state: 'OCCUPIED', lastSeenAt: new Date(), source: result.icmpReachable ? 'ICMP' : 'TCP' } }); if (Array.isArray(result.openPorts)) { for (const port of result.openPorts.filter((value): value is number => typeof value === 'number')) await this.prisma.service.upsert({ where: { hostId_protocol_port: { hostId: host.id, protocol: 'TCP', port } }, create: { hostId: host.id, name: `TCP/${port}`, protocol: 'TCP', port, status: 'OPEN' }, update: { status: 'OPEN' } }); } } await this.auditChange(user, `DISCOVERY_RESULT_${dto.status}`, 'DiscoveryResult', id, { address: result.address }); return reviewed; }
}
