import { ConflictException, ForbiddenException, Injectable, NotFoundException, OnModuleInit, StreamableFile } from '@nestjs/common';
import { PrismaClient } from '@simoes/database';
import { AuditService } from '../audit/audit.service';
import { AuthenticatedUser } from '../auth/auth.service';
import { CreateAssetDto, CreateBuildingDto, CreateDeviceDto, CreateDeviceModelDto, CreateInterfaceDto, CreateRackDto, CreateRackModelDto, CreateRoomDto, DetectPortLayoutDto, PlaceDeviceDto, ReorderRacksDto, UpdateBuildingDto, UpdateDeviceDto, UpdateDeviceModelDto, UpdateInterfaceDto, UpdateRackDto, UpdateRackModelDto, UpdateRoomDto } from './dto';
import { planRackPlacement } from './rack-placement';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { extname, join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { InfrastructureAccessService } from './infrastructure-access.service';

function naturalInterfaceCompare(a: any, b: any) {
  const tokenize = (value: string) => value.toLocaleLowerCase().split(/(\d+)/).map((part) => /^\d+$/.test(part) ? Number(part) : part);
  const left = tokenize(a.name || a.portKey || '');
  const right = tokenize(b.name || b.portKey || '');
  for (let i = 0; i < Math.max(left.length, right.length); i += 1) {
    if (left[i] === undefined) return -1;
    if (right[i] === undefined) return 1;
    if (left[i] === right[i]) continue;
    return left[i] < right[i] ? -1 : 1;
  }
  return String(a.portKey || '').localeCompare(String(b.portKey || ''));
}

type CatalogEntry = readonly [string, string, string, number, boolean, number | null, string | null];

const DEFAULT_DEVICE_MODELS: readonly CatalogEntry[] = [
  ['Cisco', 'Catalyst 2960-X', 'SWITCH', 24, true, 24, 'ethernet'], ['Cisco', 'Catalyst 9200', 'SWITCH', 24, true, 24, 'ethernet'], ['Cisco', 'Catalyst 9300', 'SWITCH', 48, true, 48, 'ethernet'], ['Cisco', 'Catalyst 9500', 'SWITCH', 24, true, 24, 'sfp'], ['Cisco', 'Nexus 9300', 'SWITCH', 48, true, 48, 'qsfp/sfp'],
  ['Cisco', 'ISR 4321', 'ROUTER', 3, true, 3, 'ethernet'], ['Cisco', 'ISR 4331', 'ROUTER', 3, true, 3, 'ethernet'], ['Cisco', 'ISR 4351', 'ROUTER', 3, true, 3, 'ethernet'], ['Cisco', 'ISR 4431', 'ROUTER', 4, true, 4, 'ethernet'], ['Cisco', 'ISR 4451-X', 'ROUTER', 4, true, 4, 'ethernet'], ['Cisco', 'Catalyst 8300', 'ROUTER', 8, true, 8, 'ethernet'], ['Cisco', 'ASR 1001-X', 'ROUTER', 6, true, 6, 'ethernet'],
  ['Cisco', 'UCS C220 M4', 'SERVER', 0, false, null, null], ['Cisco', 'UCS C220 M5', 'SERVER', 0, false, null, null], ['Cisco', 'UCS C220 M6', 'SERVER', 0, false, null, null], ['Cisco', 'UCS C220 M7', 'SERVER', 0, false, null, null], ['Cisco', 'UCS C240 M5', 'SERVER', 0, false, null, null], ['Cisco', 'UCS C240 M6', 'SERVER', 0, false, null, null], ['Cisco', 'UCS C240 M7', 'SERVER', 0, false, null, null],
  ['NetApp', 'FAS2720', 'STORAGE', 0, false, null, null], ['NetApp', 'FAS2750', 'STORAGE', 0, false, null, null], ['NetApp', 'FAS2820', 'STORAGE', 0, false, null, null], ['NetApp', 'AFF A250', 'STORAGE', 0, false, null, null], ['NetApp', 'AFF A400', 'STORAGE', 0, false, null, null], ['NetApp', 'AFF A700', 'STORAGE', 0, false, null, null], ['NetApp', 'AFF A900', 'STORAGE', 0, false, null, null], ['NetApp', 'AFF C250', 'STORAGE', 0, false, null, null],
  ['Dell', 'PowerEdge R640', 'SERVER', 0, false, null, null], ['Dell', 'PowerEdge R740', 'SERVER', 0, false, null, null], ['Dell', 'PowerEdge R740xd', 'SERVER', 0, false, null, null], ['Dell', 'PowerEdge R750', 'SERVER', 0, false, null, null], ['Dell', 'PowerEdge R650', 'SERVER', 0, false, null, null],
  ['Lenovo', 'ThinkSystem SR550', 'SERVER', 0, false, null, null], ['Lenovo', 'ThinkSystem SR570', 'SERVER', 0, false, null, null], ['Lenovo', 'ThinkSystem SR630', 'SERVER', 0, false, null, null], ['Lenovo', 'ThinkSystem SR650', 'SERVER', 0, false, null, null], ['Lenovo', 'ThinkSystem SR650 V4', 'SERVER', 0, false, null, null],
];

const DEFAULT_RACK_MODELS = [['APC/Schneider Electric', 'NetShelter SX AR3350', 42], ['APC/Schneider Electric', 'NetShelter SX AR3300X', 42], ['Generic', '42U Standard Rack', 42], ['Generic', '24U Standard Rack', 24]] as const;

@Injectable()
export class InfrastructureService implements OnModuleInit {
  constructor(private readonly prisma: PrismaClient, private readonly audit: AuditService, private readonly access: InfrastructureAccessService) {}
  async onModuleInit() {
    // Mantém o catálogo base disponível em instalações novas e é seguro em
    // reinícios porque o seed usa chaves únicas e upsert.
    await this.seedDefaultCatalog();
  }
  private async log(user: AuthenticatedUser, action: string, entityType: string, entityId: string, metadata?: unknown) { await this.audit.record({ userId: user.id, action, entityType, entityId, metadata }); }
  private assertDeviceCapability(user: AuthenticatedUser, type: string) { if (user.roles.includes('ADMIN') || user.roles.includes('SYSTEMS_OPERATOR') || (user.roles.includes('NETWORK_OPERATOR') && ['SWITCH', 'ROUTER', 'FIREWALL'].includes(type))) return; throw new ForbiddenException('A role não permite gerir este tipo de equipamento.'); }
  private async assertDeviceIdCapability(user: AuthenticatedUser, id: string) { const device = await this.prisma.device.findUnique({ where: { id }, select: { type: true } }); if (!device) throw new NotFoundException('Equipamento não encontrado'); this.assertDeviceCapability(user, device.type); }
  private readonly assetDirectory = resolve(process.env.ASSET_STORAGE_PATH ?? 'data/assets');
  async listAssets(kind?: string) { return this.prisma.assetFile.findMany({ where: kind ? { kind } : {}, orderBy: { createdAt: 'desc' } }); }
  async createAsset(dto: CreateAssetDto, user: AuthenticatedUser) {
    if (!['image/svg+xml', 'image/png', 'image/jpeg', 'image/webp'].includes(dto.mimeType)) throw new ConflictException('Apenas SVG, PNG, JPEG e WebP são suportados');
    const content = Buffer.from(dto.contentBase64.replace(/^data:[^;]+;base64,/, ''), 'base64');
    if (!content.length || content.length > 10 * 1024 * 1024) throw new ConflictException('O asset deve ter entre 1 byte e 10 MB');
    await mkdir(this.assetDirectory, { recursive: true });
    const storageKey = `${randomUUID()}${extname(dto.filename).toLowerCase() || '.asset'}`;
    await writeFile(join(this.assetDirectory, storageKey), content, { flag: 'wx' });
    try {
      const duplicate = await this.prisma.assetFile.findFirst({ where: { filename: { equals: dto.filename, mode: 'insensitive' } }, select: { id: true } });
      if (duplicate) throw new ConflictException('Já existe um asset com esse nome');
      const asset = await this.prisma.assetFile.create({ data: { filename: dto.filename, storageKey, mimeType: dto.mimeType, sizeBytes: content.length, kind: dto.kind, license: dto.license } });
      await this.log(user, 'ASSET_CREATED', 'AssetFile', asset.id, { filename: asset.filename, kind: asset.kind });
      return asset;
    } catch (error) { await unlink(join(this.assetDirectory, storageKey)).catch(() => undefined); throw error; }
  }
  async assetFile(id: string) { const asset = await this.prisma.assetFile.findUnique({ where: { id } }); if (!asset) throw new NotFoundException('Asset não encontrado'); const buffer = await readFile(join(this.assetDirectory, asset.storageKey)).catch(() => { throw new NotFoundException('Ficheiro do asset não encontrado'); }); return { asset, file: new StreamableFile(buffer, { type: asset.mimeType, disposition: `inline; filename="${asset.filename.replace(/"/g, '')}"` }) }; }
  async deleteAsset(id: string, user: AuthenticatedUser) { const asset = await this.prisma.assetFile.findUnique({ where: { id } }); if (!asset) throw new NotFoundException('Asset não encontrado'); await this.prisma.$transaction(async (tx) => { await tx.deviceModel.updateMany({ where: { OR: [{ frontAssetId: id }, { backAssetId: id }, { iconAssetId: id }] }, data: { frontAssetId: null, backAssetId: null, iconAssetId: null } }); await tx.rackModel.updateMany({ where: { OR: [{ frontAssetId: id }, { iconAssetId: id }] }, data: { frontAssetId: null, iconAssetId: null } }); await tx.device.updateMany({ where: { OR: [{ frontAssetId: id }, { iconAssetId: id }] }, data: { frontAssetId: null, iconAssetId: null } }); await tx.rack.updateMany({ where: { frontAssetId: id }, data: { frontAssetId: null } }); await tx.assetFile.delete({ where: { id } }); }); await unlink(join(this.assetDirectory, asset.storageKey)).catch(() => undefined); await this.log(user, 'ASSET_DELETED', 'AssetFile', id, { filename: asset.filename, detached: true }); return { success: true, detached: true }; }
  async cleanupLegacyAssets(user: AuthenticatedUser) { const assets = await this.prisma.assetFile.findMany({ where: { filename: { in: ['fluxograma.png', 'c9300.png', 'cisco-c9300.png'], mode: 'insensitive' } } }); const removed: string[] = []; for (const asset of assets) { await this.prisma.$transaction(async (tx) => { await tx.deviceModel.updateMany({ where: { OR: [{ frontAssetId: asset.id }, { backAssetId: asset.id }, { iconAssetId: asset.id }] }, data: { frontAssetId: null, backAssetId: null, iconAssetId: null, portLayout: { set: null } } as never }); await tx.device.updateMany({ where: { OR: [{ frontAssetId: asset.id }, { iconAssetId: asset.id }] }, data: { frontAssetId: null, iconAssetId: null } }); await tx.rack.updateMany({ where: { frontAssetId: asset.id }, data: { frontAssetId: null } }); await tx.assetFile.delete({ where: { id: asset.id } }); }); await unlink(join(this.assetDirectory, asset.storageKey)).catch(() => undefined); removed.push(asset.filename); await this.log(user, 'ASSET_DELETED', 'AssetFile', asset.id, { reason: 'legacy-cleanup', filename: asset.filename }); } await this.log(user, 'LEGACY_ASSETS_CLEANED', 'AssetFile', 'legacy', { removed }); return { removed, notFound: ['fluxograma.png', 'c9300.png'].filter((name) => !removed.some((item) => item.toLowerCase() === name)), preserved: ['rack-empty-42u.png'] }; }
  async listRackModels() { return this.prisma.rackModel.findMany({ where: { active: true }, include: { iconAsset: true, frontAsset: true, _count: { select: { racks: true } } }, orderBy: [{ manufacturer: 'asc' }, { model: 'asc' }] }); }
  async createRackModel(dto: CreateRackModelDto, user: AuthenticatedUser) { try { const item = await this.prisma.rackModel.create({ data: dto as never }); await this.log(user, 'RACK_MODEL_CREATED', 'RackModel', item.id); return item; } catch { throw new ConflictException('Já existe esse modelo de bastidor'); } }
  async updateRackModel(id: string, dto: UpdateRackModelDto, user: AuthenticatedUser) { const item = await this.prisma.rackModel.update({ where: { id }, data: dto as never }).catch(() => { throw new NotFoundException('Modelo de bastidor não encontrado'); }); await this.log(user, 'RACK_MODEL_UPDATED', 'RackModel', id); return item; }
  async deleteRackModel(id: string, user: AuthenticatedUser) { const count = await this.prisma.rack.count({ where: { modelId: id } }); if (count) throw new ConflictException('O modelo está associado a bastidores'); await this.prisma.rackModel.update({ where: { id }, data: { active: false } }).catch(() => { throw new NotFoundException('Modelo de bastidor não encontrado'); }); await this.log(user, 'RACK_MODEL_ARCHIVED', 'RackModel', id); return { success: true }; }
  async listRacks(user: AuthenticatedUser, siteId?: string) { const roomIds = await this.access.visibleRoomIds(user, siteId); return this.prisma.rack.findMany({ where: { roomId: { in: roomIds }, ...(siteId ? { room: { building: { siteId } } } : {}) }, include: { model: { include: { frontAsset: true, iconAsset: true } }, frontAsset: true, room: { include: { building: { include: { site: true } } } }, devices: { include: { model: { include: { frontAsset: true, iconAsset: true } }, frontAsset: true, iconAsset: true }, orderBy: { rackUnitStart: 'asc' } } }, orderBy: [{ roomId: 'asc' }, { displayOrder: 'asc' }, { name: 'asc' }] }); }
  async listLocations(user: AuthenticatedUser, siteId: string) { const [buildingIds, roomIds] = await Promise.all([this.access.visibleBuildingIds(user, siteId), this.access.visibleRoomIds(user, siteId)]); return this.prisma.building.findMany({ where: { siteId, id: { in: buildingIds } }, include: { rooms: { where: { id: { in: roomIds } }, include: { racks: true, building: true }, orderBy: { name: 'asc' } } }, orderBy: { name: 'asc' } }); }
  async listBuildings(user: AuthenticatedUser, siteId: string) { const [buildingIds, roomIds] = await Promise.all([this.access.visibleBuildingIds(user, siteId), this.access.visibleRoomIds(user, siteId)]); return this.prisma.building.findMany({ where: { siteId, id: { in: buildingIds } }, include: { rooms: { where: { id: { in: roomIds } }, include: { racks: true }, orderBy: { name: 'asc' } } }, orderBy: { name: 'asc' } }); }
  async createBuilding(siteId: string, dto: CreateBuildingDto, user: AuthenticatedUser) { await this.access.assertSite(user, 'CREATE', siteId); const site = await this.prisma.site.findUnique({ where: { id: siteId } }); if (!site) throw new NotFoundException('Site não encontrado'); try { const item = await this.prisma.building.create({ data: { ...dto, siteId } }); await this.log(user, 'BUILDING_CREATED', 'Building', item.id, { siteId }); return item; } catch { throw new ConflictException('Já existe um edifício com esse nome neste Site'); } }
  async updateBuilding(id: string, dto: UpdateBuildingDto, user: AuthenticatedUser) { await this.access.assertBuilding(user, 'UPDATE', id); try { const item = await this.prisma.building.update({ where: { id }, data: dto }); await this.log(user, 'BUILDING_UPDATED', 'Building', id); return item; } catch { throw new NotFoundException('Edifício não encontrado'); } }
  async deleteBuilding(id: string, user: AuthenticatedUser) { await this.access.assertBuilding(user, 'DELETE', id); const item = await this.prisma.building.findUnique({ where: { id }, include: { rooms: true } }); if (!item) throw new NotFoundException('Edifício não encontrado'); if (item.rooms.length) throw new ConflictException('O edifício ainda contém salas'); await this.prisma.building.delete({ where: { id } }); await this.log(user, 'BUILDING_DELETED', 'Building', id); return { success: true }; }
  async listRooms(user: AuthenticatedUser, buildingId: string) { await this.access.assertBuilding(user, 'READ', buildingId); const roomIds = await this.access.visibleRoomIds(user); return this.prisma.room.findMany({ where: { buildingId, id: { in: roomIds } }, include: { racks: true, building: true }, orderBy: { name: 'asc' } }); }
  async createRoom(buildingId: string, dto: CreateRoomDto, user: AuthenticatedUser) { await this.access.assertBuilding(user, 'CREATE', buildingId); const building = await this.prisma.building.findUnique({ where: { id: buildingId } }); if (!building) throw new NotFoundException('Edifício não encontrado'); try { const item = await this.prisma.room.create({ data: { ...dto, buildingId } }); await this.log(user, 'ROOM_CREATED', 'Room', item.id, { buildingId }); return item; } catch { throw new ConflictException('Já existe uma sala com esse nome neste edifício'); } }
  async updateRoom(id: string, dto: UpdateRoomDto, user: AuthenticatedUser) { await this.access.assertRoom(user, 'UPDATE', id); try { const item = await this.prisma.room.update({ where: { id }, data: dto }); await this.log(user, 'ROOM_UPDATED', 'Room', id); return item; } catch { throw new NotFoundException('Sala não encontrada'); } }
  async deleteRoom(id: string, user: AuthenticatedUser) { await this.access.assertRoom(user, 'DELETE', id); const item = await this.prisma.room.findUnique({ where: { id }, include: { racks: true } }); if (!item) throw new NotFoundException('Sala não encontrada'); if (item.racks.length) throw new ConflictException('A sala ainda contém bastidores'); await this.prisma.room.delete({ where: { id } }); await this.log(user, 'ROOM_DELETED', 'Room', id); return { success: true }; }
  async getRack(id: string, user: AuthenticatedUser) { await this.access.assertRack(user, 'READ', id); const item = await this.prisma.rack.findUnique({ where: { id }, include: { model: { include: { frontAsset: true, iconAsset: true } }, frontAsset: true, room: { include: { building: { include: { site: true } } } }, devices: { include: { model: { include: { frontAsset: true, iconAsset: true } }, frontAsset: true, iconAsset: true }, orderBy: { rackUnitStart: 'asc' } } } }); if (!item) throw new NotFoundException('Bastidor não encontrado'); return item; }
  async createRack(dto: CreateRackDto, user: AuthenticatedUser) { await this.access.assertRoom(user, 'CREATE', dto.roomId); const room = await this.prisma.room.findUnique({ where: { id: dto.roomId } }); if (!room) throw new NotFoundException('Sala não encontrada'); const lastRack = await this.prisma.rack.findFirst({ where: { roomId: dto.roomId }, orderBy: { displayOrder: 'desc' }, select: { displayOrder: true } }); const item = await this.prisma.rack.create({ data: { ...dto, displayOrder: (lastRack?.displayOrder ?? -1) + 1, units: 42, modelId: null, frontAssetId: null } }); await this.log(user, 'RACK_CREATED', 'Rack', item.id); return this.getRack(item.id, user); }
  async reorderRacks(roomId: string, dto: ReorderRacksDto, user: AuthenticatedUser) { await this.access.assertRoom(user, 'UPDATE', roomId); const racks = await this.prisma.rack.findMany({ where: { roomId }, select: { id: true } }); if (!racks.length) throw new NotFoundException('Sala ou bastidores não encontrados'); const expectedIds = new Set(racks.map((rack) => rack.id)); const receivedIds = new Set(dto.rackIds); if (receivedIds.size !== dto.rackIds.length || receivedIds.size !== expectedIds.size || dto.rackIds.some((id) => !expectedIds.has(id))) throw new ConflictException('A ordem tem de incluir todos os bastidores da sala uma única vez'); await this.prisma.$transaction(dto.rackIds.map((id, displayOrder) => this.prisma.rack.update({ where: { id }, data: { displayOrder } }))); await this.log(user, 'RACKS_REORDERED', 'Room', roomId, { rackIds: dto.rackIds }); return this.prisma.rack.findMany({ where: { roomId }, orderBy: [{ displayOrder: 'asc' }, { name: 'asc' }] }); }
  async updateRack(id: string, dto: UpdateRackDto, user: AuthenticatedUser) { const [room, current] = await Promise.all([this.prisma.room.findUnique({ where: { id: dto.roomId } }), this.prisma.rack.findUnique({ where: { id }, select: { roomId: true } })]); if (!room) throw new NotFoundException('Sala não encontrada'); if (!current) throw new NotFoundException('Bastidor não encontrado'); await this.access.assertRoom(user, 'UPDATE', current.roomId); if (current.roomId !== dto.roomId) await this.access.assertRoom(user, 'UPDATE', dto.roomId); const movingRoom = current.roomId !== dto.roomId; const lastRack = movingRoom ? await this.prisma.rack.findFirst({ where: { roomId: dto.roomId }, orderBy: { displayOrder: 'desc' }, select: { displayOrder: true } }) : null; const item = await this.prisma.rack.update({ where: { id }, data: { ...dto, ...(movingRoom ? { displayOrder: (lastRack?.displayOrder ?? -1) + 1 } : {}), units: 42, modelId: null, frontAssetId: null } }); await this.log(user, 'RACK_UPDATED', 'Rack', id); return this.getRack(item.id, user); }
  async deleteRack(id: string, user: AuthenticatedUser) {
    await this.access.assertRack(user, 'DELETE', id);
    const rack = await this.prisma.$transaction(async (tx) => {
      const item = await tx.rack.findUnique({ where: { id }, include: { devices: true } });
      if (!item) throw new NotFoundException('Bastidor não encontrado');
      if (item.devices.length) throw new ConflictException('O bastidor ainda contém equipamentos');

      await tx.rack.delete({ where: { id } });
      await tx.rack.updateMany({
        where: { roomId: item.roomId, displayOrder: { gt: item.displayOrder } },
        data: { displayOrder: { decrement: 1 } },
      });
      return item;
    });
    await this.log(user, 'RACK_DELETED', 'Rack', id, { roomId: rack.roomId, displayOrder: rack.displayOrder });
    return { success: true };
  }
  private async visibleDeviceWhere(user: AuthenticatedUser) { const roomIds = await this.access.visibleRoomIds(user); return { OR: [{ rackId: null }, { rack: { roomId: { in: roomIds } } }] }; }
  async listModels(user: AuthenticatedUser, search?: string, type?: string, networkPorts?: string) { const deviceWhere = await this.visibleDeviceWhere(user); return this.prisma.deviceModel.findMany({ where: { ...(type ? { type } : {}), ...(networkPorts === 'true' ? { supportsNetworkPorts: true } : {}), ...(search ? { OR: [{ manufacturer: { contains: search, mode: 'insensitive' } }, { model: { contains: search, mode: 'insensitive' } }] } : {}) }, include: { frontAsset: true, iconAsset: true, _count: { select: { devices: { where: deviceWhere } } } }, orderBy: [{ manufacturer: 'asc' }, { model: 'asc' }] }); }
  async getModel(id: string, user: AuthenticatedUser) { const deviceWhere = await this.visibleDeviceWhere(user); const item = await this.prisma.deviceModel.findUnique({ where: { id }, include: { frontAsset: true, iconAsset: true, devices: { where: deviceWhere } } }); if (!item) throw new NotFoundException('Modelo não encontrado'); return item; }
  async seedCatalog(user: AuthenticatedUser) {
    const catalog = DEFAULT_DEVICE_MODELS;
    let created = 0; let existing = 0;
    for (const [manufacturer, model, type, portCount, supportsNetworkPorts, networkPortCount, family] of catalog) {
      const found = await this.prisma.deviceModel.findUnique({ where: { manufacturer_model: { manufacturer, model } }, select: { id: true } });
      await this.prisma.deviceModel.upsert({ where: { manufacturer_model: { manufacturer, model } }, create: { manufacturer, model, type, portCount, supportsNetworkPorts, networkPortCount, portLayout: family ? { family, ports: networkPortCount } : null } as never, update: { type, portCount, supportsNetworkPorts, networkPortCount } as never });
      if (found) existing++; else created++;
    }
    const racks = DEFAULT_RACK_MODELS;
    let rackCreated = 0; let rackExisting = 0;
    for (const [manufacturer, model, units] of racks) { const found = await this.prisma.rackModel.findUnique({ where: { manufacturer_model: { manufacturer, model } }, select: { id: true } }); await this.prisma.rackModel.upsert({ where: { manufacturer_model: { manufacturer, model } }, create: { manufacturer, model, units }, update: { units } }); if (found) rackExisting++; else rackCreated++; }
    await this.log(user, 'DEVICE_CATALOG_SEEDED', 'DeviceModel', 'catalog', { created, existing, rackCreated, rackExisting });
    return { created, existing, rackCreated, rackExisting, total: catalog.length, rackTotal: racks.length };
  }
  private async seedDefaultCatalog() {
    for (const [manufacturer, model, type, portCount, supportsNetworkPorts, networkPortCount, family] of DEFAULT_DEVICE_MODELS) {
      await this.prisma.deviceModel.upsert({ where: { manufacturer_model: { manufacturer, model } }, create: { manufacturer, model, type, portCount, supportsNetworkPorts, networkPortCount, portLayout: family ? { family, ports: networkPortCount } : null } as never, update: { type, portCount, supportsNetworkPorts, networkPortCount } as never });
    }
    for (const [manufacturer, model, units] of DEFAULT_RACK_MODELS) {
      await this.prisma.rackModel.upsert({ where: { manufacturer_model: { manufacturer, model } }, create: { manufacturer, model, units }, update: { units } });
    }
  }
  async createModel(dto: CreateDeviceModelDto, user: AuthenticatedUser) { try { const item = await this.prisma.deviceModel.create({ data: dto as never }); await this.log(user, 'DEVICE_MODEL_CREATED', 'DeviceModel', item.id); return item; } catch { throw new ConflictException('Já existe esse modelo'); } }
  async updateModel(id: string, dto: UpdateDeviceModelDto, user: AuthenticatedUser) { const item = await this.prisma.deviceModel.update({ where: { id }, data: dto as never }).catch(() => { throw new NotFoundException('Modelo não encontrado'); }); await this.log(user, 'DEVICE_MODEL_UPDATED', 'DeviceModel', id); return item; }
  async deleteModel(id: string, user: AuthenticatedUser) { await this.prisma.deviceModel.delete({ where: { id } }).catch(() => { throw new NotFoundException('Modelo não encontrado'); }); await this.log(user, 'DEVICE_MODEL_DELETED', 'DeviceModel', id); return { success: true }; }
  async listDevices(user: AuthenticatedUser, search?: string, type?: string, siteId?: string, pageText?: string, pageSizeText?: string) { const page = Math.max(Number(pageText) || 1, 1); const pageSize = Math.min(Math.max(Number(pageSizeText) || 25, 1), 100); const [roomIds, unplacedSiteIds] = await Promise.all([this.access.visibleRoomIds(user, siteId), this.access.visibleUnplacedSiteIds(user, siteId)]); const where = { AND: [{ OR: [{ rackId: null, siteId: { in: unplacedSiteIds } }, { rack: { roomId: { in: roomIds } } }] }, ...(type ? [{ type }] : []), ...(siteId ? [{ siteId }] : []), ...(search ? [{ OR: [{ name: { contains: search, mode: 'insensitive' as const } }, { hostname: { contains: search, mode: 'insensitive' as const } }, { serialNumber: { contains: search, mode: 'insensitive' as const } }, { assetTag: { contains: search, mode: 'insensitive' as const } }, { managementIp: { contains: search } }] }] : [])] }; const [items, total] = await Promise.all([this.prisma.device.findMany({ where, include: { model: { include: { frontAsset: true, iconAsset: true } }, frontAsset: true, iconAsset: true, site: true, rack: { include: { room: { include: { building: true } } } }, _count: { select: { interfaces: true, ipAddresses: true } } }, orderBy: { name: 'asc' }, skip: (page - 1) * pageSize, take: pageSize }), this.prisma.device.count({ where })]); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
  async getDevice(id: string, user: AuthenticatedUser) { await this.access.assertDevice(user, 'READ', id); const item = await this.prisma.device.findUnique({ where: { id }, include: { model: { include: { frontAsset: true, iconAsset: true } }, frontAsset: true, iconAsset: true, site: true, rack: { include: { room: { include: { building: true } } } }, interfaces: { include: { nativeVlan: this.vlanInclude, accessVlan: this.vlanInclude, allowedVlans: { include: { vlan: this.vlanInclude } }, ipAddresses: { include: { subnet: true, host: true } } } }, ipAddresses: { include: { subnet: true, host: true } } } }); if (!item) throw new NotFoundException('Equipamento não encontrado'); item.interfaces.sort(naturalInterfaceCompare); return item; }
  private async validateDeviceModel(modelId?: string) { if (!modelId) return; const model = await this.prisma.deviceModel.findUnique({ where: { id: modelId }, select: { model: true, supportsNetworkPorts: true, networkPortCount: true, portCount: true, portLayout: true } }); if (!model) throw new NotFoundException('Modelo não encontrado'); const ports = (model.portLayout as any)?.ports; if (!Array.isArray(ports) || !ports.length) throw new ConflictException('O modelo tem de ter as portas mapeadas antes de criar o equipamento'); }
  private async validateDeviceFrontAsset(frontAssetId?: string) { if (!frontAssetId) throw new ConflictException('O equipamento tem de ter a imagem frontal definida'); const asset = await this.prisma.assetFile.count({ where: { id: frontAssetId } }); if (asset !== 1) throw new NotFoundException('A imagem frontal selecionada não foi encontrada'); }
  private async validateRackPlacement(dto: CreateDeviceDto, deviceId?: string) { if (!dto.rackId) return; if (!dto.rackUnitStart || !dto.rackUnitSize) throw new ConflictException('Define a unidade inicial e o tamanho do equipamento'); const rack = await this.prisma.rack.findUnique({ where: { id: dto.rackId }, include: { room: { include: { building: true } }, devices: true } }); if (!rack) throw new NotFoundException('Bastidor não encontrado'); if (dto.rackUnitStart < 1 || dto.rackUnitStart + dto.rackUnitSize - 1 > rack.units) throw new ConflictException('A posição do equipamento excede as unidades do bastidor'); if (dto.siteId && dto.siteId !== rack.room.building.siteId) throw new ConflictException('O bastidor não pertence ao Site selecionado'); const end = dto.rackUnitStart + dto.rackUnitSize - 1; const overlap = rack.devices.some((device) => device.id !== deviceId && device.rackUnitStart && device.rackUnitSize && dto.rackUnitStart! <= device.rackUnitStart + device.rackUnitSize - 1 && end >= device.rackUnitStart); if (overlap) throw new ConflictException('A posição indicada já está ocupada no bastidor'); }
  async createDevice(dto: CreateDeviceDto, user: AuthenticatedUser) { this.assertDeviceCapability(user, dto.type); if (dto.rackId) await this.access.assertRack(user, 'CREATE', dto.rackId); else if (dto.siteId) await this.access.assertSite(user, 'CREATE', dto.siteId); else throw new ConflictException('Seleciona um Site ou bastidor para o equipamento'); await this.validateDeviceModel(dto.modelId); await this.validateDeviceFrontAsset(dto.frontAssetId); await this.validateRackPlacement(dto); try { const data = { ...dto, status: (dto.rackId && dto.status !== 'RETIRED' ? 'ACTIVE' : (dto.status ?? 'UNKNOWN')) as never } as any; delete data.managementIpAddressId; const item = await this.prisma.device.create({ data }); if (dto.managementIpAddressId) await this.prisma.ipAddress.update({ where: { id: dto.managementIpAddressId }, data: { deviceId: item.id } }).catch(() => { throw new ConflictException('IP de gestão não encontrado'); }); await this.log(user, 'DEVICE_CREATED', 'Device', item.id); return this.getDevice(item.id, user); } catch (error) { if (error instanceof ConflictException) throw error; throw new ConflictException('Não foi possível criar o equipamento'); } }
  private async buildDevicePlacementPlan(client: any, id: string, dto: PlaceDeviceDto) {
    const device = await client.device.findUnique({ where: { id }, include: { rack: { include: { room: { include: { building: true } } } } } });
    if (!device) throw new NotFoundException('Equipamento não encontrado');
    if (!device.rackId || !device.rackUnitStart || !device.rackUnitSize) throw new ConflictException('O equipamento tem de estar posicionado num bastidor antes de ser arrastado');
    const targetRack = await client.rack.findUnique({ where: { id: dto.rackId }, include: { room: { include: { building: true } } } });
    if (!targetRack) throw new NotFoundException('Bastidor de destino não encontrado');
    if (targetRack.roomId !== device.rack.roomId) throw new ConflictException('Só é possível mover equipamentos entre bastidores da mesma sala');
    if (targetRack.room.building.siteId !== device.rack.room.building.siteId) throw new ConflictException('O bastidor não pertence ao Site do equipamento');

    const rackIds = [...new Set([device.rackId, dto.rackId])];
    const racks = await client.rack.findMany({
      where: { id: { in: rackIds } },
      include: { devices: { where: { status: { not: 'RETIRED' } } } },
    });
    try {
      return planRackPlacement(
        racks.map((rack: any) => ({
          id: rack.id,
          name: rack.name,
          units: rack.units,
          devices: rack.devices
            .filter((item: any) => item.rackUnitStart && item.rackUnitSize)
            .map((item: any) => ({ id: item.id, name: item.name, rackId: rack.id, rackUnitStart: item.rackUnitStart, rackUnitSize: item.rackUnitSize })),
        })),
        id,
        dto.rackId,
        dto.rackUnitStart,
      );
    } catch (error) {
      throw new ConflictException(error instanceof Error ? error.message : 'Não foi possível posicionar o equipamento');
    }
  }
  async previewDevicePlacement(id: string, dto: PlaceDeviceDto, user: AuthenticatedUser) { await Promise.all([this.access.assertDevice(user, 'UPDATE', id), this.access.assertRack(user, 'UPDATE', dto.rackId), this.assertDeviceIdCapability(user, id)]); return this.buildDevicePlacementPlan(this.prisma, id, dto); }
  async placeDevice(id: string, dto: PlaceDeviceDto, user: AuthenticatedUser) {
    await Promise.all([this.access.assertDevice(user, 'UPDATE', id), this.access.assertRack(user, 'UPDATE', dto.rackId), this.assertDeviceIdCapability(user, id)]);
    const plan = await this.prisma.$transaction(async (tx) => {
      const next = await this.buildDevicePlacementPlan(tx, id, dto);
      for (const change of next.changes) {
        const rack = await tx.rack.findUnique({ where: { id: change.rackId }, select: { room: { select: { building: { select: { siteId: true } } } } } });
        await tx.device.update({ where: { id: change.id }, data: { rackId: change.rackId, rackUnitStart: change.rackUnitStart, siteId: rack!.room.building.siteId, status: 'ACTIVE' } });
      }
      return next;
    }, { isolationLevel: 'Serializable' });
    await this.log(user, 'DEVICE_PLACEMENT_UPDATED', 'Device', id, { changes: plan.changes });
    return plan;
  }
  async updateDevice(id: string, dto: UpdateDeviceDto, user: AuthenticatedUser) { const current = await this.prisma.device.findUnique({ where: { id }, select: { status: true, rackId: true, frontAssetId: true, type: true } }); if (!current) throw new NotFoundException('Equipamento não encontrado'); this.assertDeviceCapability(user, current.type); this.assertDeviceCapability(user, dto.type); await this.access.assertDevice(user, 'UPDATE', id); if (dto.rackId && dto.rackId !== current.rackId) await this.access.assertRack(user, 'UPDATE', dto.rackId); await this.validateDeviceFrontAsset(dto.frontAssetId ?? current.frontAssetId ?? undefined); await this.validateRackPlacement(dto, id); const status = dto.rackId && current.status !== 'RETIRED' ? 'ACTIVE' : (dto.status ?? current.status); const data = { ...dto, status: status as never, managementIpAddressId: undefined } as any; delete data.managementIpAddressId; const item = await this.prisma.device.update({ where: { id }, data }).catch(() => { throw new NotFoundException('Equipamento não encontrado'); }); if (dto.managementIpAddressId) await this.prisma.ipAddress.update({ where: { id: dto.managementIpAddressId }, data: { deviceId: id } }).catch(() => { throw new ConflictException('IP de gestão não encontrado'); }); await this.log(user, 'DEVICE_UPDATED', 'Device', id, { rackId: dto.rackId, managementIp: dto.managementIp, managementIpAddressId: dto.managementIpAddressId }); return this.getDevice(item.id, user); }
  async deleteDevice(id: string, user: AuthenticatedUser) { await this.access.assertDevice(user, 'DELETE', id); await this.prisma.device.update({ where: { id }, data: { status: 'RETIRED' } }).catch(() => { throw new NotFoundException('Equipamento não encontrado'); }); await this.log(user, 'DEVICE_RETIRED', 'Device', id); return { success: true }; }
  private readonly vlanInclude = { include: { subnets: { take: 1, orderBy: { id: 'asc' as const } } } };
  async listInterfaces(user: AuthenticatedUser, deviceId?: string, search?: string) { if (deviceId) await this.access.assertDevice(user, 'READ', deviceId); const [roomIds, unplacedSiteIds] = deviceId ? [[], []] : await Promise.all([this.access.visibleRoomIds(user), this.access.visibleUnplacedSiteIds(user)]); const items = await this.prisma.deviceInterface.findMany({ where: { ...(deviceId ? { deviceId } : { device: { OR: [{ rackId: null, siteId: { in: unplacedSiteIds } }, { rack: { roomId: { in: roomIds } } }] } }), ...(search ? { OR: [{ name: { contains: search, mode: 'insensitive' } }, { description: { contains: search, mode: 'insensitive' } }] } : {}) }, include: { device: { include: { model: true } }, nativeVlan: this.vlanInclude, accessVlan: this.vlanInclude, allowedVlans: { include: { vlan: this.vlanInclude } }, ipAddresses: { include: { subnet: true, host: true } } } }); const natural = (value: string) => value.toLocaleLowerCase().split(/(\d+)/).map((part) => /^\d+$/.test(part) ? Number(part) : part); const compare = (a: any, b: any) => { const aa = natural(a.name ?? a.portKey ?? ''); const bb = natural(b.name ?? b.portKey ?? ''); for (let index = 0; index < Math.max(aa.length, bb.length); index++) { if (aa[index] === undefined) return -1; if (bb[index] === undefined) return 1; if (aa[index] === bb[index]) continue; return aa[index] < bb[index] ? -1 : 1; } return String(a.name).localeCompare(String(b.name)); }; return items.sort((a, b) => a.deviceId.localeCompare(b.deviceId) || compare(a, b)); }
  async getInterface(id: string, user: AuthenticatedUser) { await this.access.assertInterface(user, 'READ', id); const item = await this.prisma.deviceInterface.findUnique({ where: { id }, include: { device: { include: { model: true } }, nativeVlan: this.vlanInclude, accessVlan: this.vlanInclude, allowedVlans: { include: { vlan: this.vlanInclude } }, ipAddresses: { include: { subnet: true, host: true } } } }); if (!item) throw new NotFoundException('Interface não encontrada'); return item; }
  async createInterface(deviceId: string, dto: CreateInterfaceDto, user: AuthenticatedUser) { await Promise.all([this.access.assertDevice(user, 'CREATE', deviceId), this.assertDeviceIdCapability(user, deviceId)]); try { const { allowedVlanIds, ...fields } = dto; const item = await this.prisma.deviceInterface.create({ data: { ...fields, deviceId, allowedVlans: { create: (allowedVlanIds ?? []).map((vlanId) => ({ vlanId })) } } as never }); await this.log(user, 'DEVICE_INTERFACE_CREATED', 'DeviceInterface', item.id); return this.getInterface(item.id, user); } catch { throw new ConflictException('Não foi possível criar a interface'); } }
  async updateInterface(id: string, dto: UpdateInterfaceDto, user: AuthenticatedUser) { await this.access.assertInterface(user, 'UPDATE', id); const { allowedVlanIds, id: _ignoredId, source: _ignoredSource, lastSeenAt: _ignoredLastSeenAt, deviceId: _ignoredDeviceId, device: _ignoredDevice, nativeVlan: _ignoredNativeVlan, accessVlan: _ignoredAccessVlan, allowedVlans: _ignoredAllowedVlans, ipAddresses: _ignoredIpAddresses, ...fields } = dto; const item = await this.prisma.deviceInterface.update({ where: { id }, data: { ...fields, allowedVlans: allowedVlanIds ? { deleteMany: {}, create: allowedVlanIds.map((vlanId) => ({ vlanId })) } : undefined } as never }).catch(() => { throw new NotFoundException('Interface não encontrada'); }); await this.log(user, 'DEVICE_INTERFACE_UPDATED', 'DeviceInterface', id); return this.getInterface(item.id, user); }
  async generateInterfaces(deviceId: string, user: AuthenticatedUser) { await Promise.all([this.access.assertDevice(user, 'CREATE', deviceId), this.assertDeviceIdCapability(user, deviceId)]); const device = await this.prisma.device.findUnique({ where: { id: deviceId }, include: { model: true, interfaces: { select: { name: true, portKey: true } } } }); if (!device) throw new NotFoundException('Equipamento não encontrado'); const layout = (device.model?.portLayout as any)?.ports; const count = device.model?.networkPortCount ?? device.model?.portCount ?? 0; const ports = Array.isArray(layout) && layout.length ? layout : Array.from({ length: count }, (_, index) => ({ portKey: `ethernet1/${index + 1}`, label: `${index + 1}`, interfaceType: 'ETHERNET' })); const existing = new Set(device.interfaces.map((item) => item.portKey || item.name)); let created = 0; for (const port of ports) { const name = String(port.label || port.portKey); if (existing.has(String(port.portKey)) || existing.has(name)) continue; await this.prisma.deviceInterface.create({ data: { deviceId, name, portKey: String(port.portKey), interfaceType: String(port.interfaceType ?? 'ETHERNET'), adminUp: true, operUp: false } as never }); created++; } await this.log(user, 'DEVICE_INTERFACES_GENERATED', 'Device', deviceId, { created, total: ports.length }); return { created, total: ports.length }; }
  async deleteInterface(id: string, user: AuthenticatedUser) { await this.access.assertInterface(user, 'DELETE', id); await this.prisma.deviceInterface.delete({ where: { id } }).catch(() => { throw new NotFoundException('Interface não encontrada'); }); await this.log(user, 'DEVICE_INTERFACE_DELETED', 'DeviceInterface', id); return { success: true }; }
  async getPortLayout(id: string) { const item = await this.prisma.deviceModel.findUnique({ where: { id }, select: { id: true, model: true, frontAsset: true, portLayout: true, networkPortCount: true } }); if (!item) throw new NotFoundException('Modelo não encontrado'); return item; }
  async setModelFrontAsset(id: string, assetId: string, user: AuthenticatedUser) { const asset = await this.prisma.assetFile.findUnique({ where: { id: assetId } }); if (!asset) throw new NotFoundException('Asset não encontrado'); const item = await this.prisma.deviceModel.update({ where: { id }, data: { frontAssetId: assetId } }).catch(() => { throw new NotFoundException('Modelo não encontrado'); }); await this.log(user, 'ASSET_ASSOCIATED', 'DeviceModel', id, { assetId, role: 'front' }); return item; }
  async detectPortLayout(id: string, dto: DetectPortLayoutDto) { const model = await this.prisma.deviceModel.findUnique({ where: { id }, select: { networkPortCount: true, portCount: true, model: true } }); if (!model) throw new NotFoundException('Modelo não encontrado'); const count = dto.portCount ?? model.networkPortCount ?? model.portCount ?? 0; if (!count) throw new ConflictException('Define primeiro o número de portas do modelo'); const columns = Math.min(dto.columns ?? (count > 24 ? 24 : count), count); const rows = Math.ceil(count / columns); const type = dto.portType ?? 'GIGABIT_ETHERNET'; const ports = Array.from({ length: count }, (_, index) => ({ portKey: `ethernet1/${index + 1}`, label: `Gi1/${index + 1}`, interfaceType: type, x: ((index % columns) + 0.5) / columns, y: ((Math.floor(index / columns)) + 0.5) / rows, width: 0.62 / columns, height: 0.34 / rows })); return { imageWidth: dto.imageWidth ?? 1000, imageHeight: dto.imageHeight ?? 300, confidence: 0.35, ports, warnings: ['A deteção atual é uma grelha geométrica, não uma análise da imagem; confirma as zonas antes de guardar.'] }; }
  async updatePortLayout(id: string, dto: { imageWidth?: number; imageHeight?: number; ports?: unknown[]; viewport?: unknown; confidence?: number; confirmedAt?: string; confirmedBy?: string; warnings?: unknown; assetId?: string }, user: AuthenticatedUser) { const model = await this.prisma.deviceModel.findUnique({ where: { id }, select: { portLayout: true } }); if (!model) throw new NotFoundException('Modelo não encontrado'); const { assetId, warnings: _warnings, ...layoutData } = dto; const layout = { ...((model.portLayout as Record<string, unknown> | null) ?? {}), ...layoutData }; const item = await this.prisma.deviceModel.update({ where: { id }, data: { portLayout: layout, frontAssetId: assetId || undefined } as never }); await this.log(user, 'DEVICE_MODEL_PORT_LAYOUT_UPDATED', 'DeviceModel', id, { ports: Array.isArray(dto.ports) ? dto.ports.length : undefined, assetId }); return item;
  }
  async generatePortLayout(id: string, user: AuthenticatedUser) { const model = await this.prisma.deviceModel.findUnique({ where: { id }, select: { networkPortCount: true, portCount: true, portLayout: true } }); if (!model) throw new NotFoundException('Modelo não encontrado'); const count = model.networkPortCount ?? model.portCount ?? 0; const columns = Math.min(24, Math.max(1, count)); const rows = Math.ceil(count / columns); const ports = Array.from({ length: count }, (_, index) => ({ portKey: `ethernet1/${index + 1}`, label: `${index + 1}`, interfaceType: 'RJ45', x: (index % columns + 0.5) / columns, y: (Math.floor(index / columns) + 0.5) / rows, width: 0.62 / columns, height: 0.34 / rows })); return this.updatePortLayout(id, { imageWidth: 1000, imageHeight: 300, ports }, user); }
}
