import { createHash } from 'node:crypto';
import { mkdir, rename, writeFile } from 'node:fs/promises';
import { hostname, networkInterfaces } from 'node:os';
import { dirname, resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { PrismaClient } from '@simoes/database';
import { log, publicErrorCode } from './log';
import { runtimeIpv4Interfaces, SnmpRuntimeInterface } from './traps';

type ListenerConfig = { listenAll: boolean; selectedInterfaces: unknown } | null;
type SelectedInterface = { instanceId: string; name: string; address: string };

function dockerEnvironment() {
  return Object.fromEntries(['PATH', 'HOME', 'DOCKER_HOST', 'DOCKER_CONTEXT'].flatMap((name) => process.env[name] ? [[name, process.env[name]!]] : []));
}

export function selectedHostAddresses(config: ListenerConfig, current: SnmpRuntimeInterface[]) {
  if (config?.listenAll ?? true) return ['0.0.0.0'];
  if (!Array.isArray(config?.selectedInterfaces)) return [];
  const selected = config.selectedInterfaces as SelectedInterface[];
  return [...new Set(current.filter((item) => selected.some((candidate) => candidate
    && candidate.instanceId === item.instanceId
    && candidate.name === item.name
    && candidate.address === item.address)).map((item) => item.address))].sort();
}

export function renderComposeOverride(addresses: string[], publishedPort: number) {
  const ports = addresses.length
    ? addresses.map((address) => [
      '      - target: 1162',
      `        published: ${JSON.stringify(String(publishedPort))}`,
      '        protocol: udp',
      `        host_ip: ${JSON.stringify(address)}`,
    ].join('\n')).join('\n')
    : '      []';
  return `# Generated by the SNMP host agent. Do not edit.\nservices:\n  snmp:\n    ports:\n${ports}\n`;
}

function positiveInteger(value: string | undefined, fallback: number, name: string) {
  const parsed = Number(value ?? fallback);
  if (!Number.isSafeInteger(parsed) || parsed <= 0 || parsed > 65_535) {
    throw Object.assign(new Error(`${name}_INVALID`), { code: `${name}_INVALID` });
  }
  return parsed;
}

async function writeAtomic(path: string, contents: string) {
  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  const temporary = `${path}.${process.pid}.tmp`;
  await writeFile(temporary, contents, { encoding: 'utf8', mode: 0o600 });
  await rename(temporary, path);
}

async function runDockerCompose(projectRoot: string, baseFile: string, overrideFile: string) {
  await new Promise<void>((resolvePromise, reject) => {
    const child = spawn('docker', ['compose', '-f', baseFile, '-f', overrideFile, '--profile', 'snmp', 'up', '-d', '--no-deps', 'snmp'], {
      cwd: projectRoot,
      env: dockerEnvironment(),
      stdio: ['ignore', 'inherit', 'inherit'],
    });
    child.once('error', reject);
    child.once('exit', (code, signal) => code === 0
      ? resolvePromise()
      : reject(Object.assign(new Error('SNMP_HOST_AGENT_DOCKER_FAILED'), { code: 'SNMP_HOST_AGENT_DOCKER_FAILED', exitCode: code, signal })));
  });
}

async function dockerOutput(args: string[], projectRoot: string) {
  return new Promise<string>((resolvePromise, reject) => {
    const child = spawn('docker', args, { cwd: projectRoot, env: dockerEnvironment(), stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    child.stdout.setEncoding('utf8').on('data', (chunk) => { stdout += chunk; });
    child.stderr.setEncoding('utf8').on('data', (chunk) => { stderr += chunk; });
    child.once('error', reject);
    child.once('exit', (code) => code === 0 ? resolvePromise(stdout.trim()) : reject(Object.assign(new Error('SNMP_HOST_AGENT_DOCKER_INSPECT_FAILED'), { code: 'SNMP_HOST_AGENT_DOCKER_INSPECT_FAILED', exitCode: code, stderr: stderr.slice(0, 500) })));
  });
}

async function composeConfigurationIsApplied(projectRoot: string, baseFile: string, overrideFile: string) {
  try {
    const composeArgs = ['compose', '-f', baseFile, '-f', overrideFile, '--profile', 'snmp'];
    const desiredOutput = await dockerOutput([...composeArgs, 'config', '--hash', 'snmp'], projectRoot);
    const desiredHash = desiredOutput.split(/\s+/).at(-1);
    const containerId = await dockerOutput([...composeArgs, 'ps', '-q', 'snmp'], projectRoot);
    if (!desiredHash || !containerId) return false;
    const appliedHash = await dockerOutput(['inspect', '--format', '{{index .Config.Labels "com.docker.compose.config-hash"}}', containerId], projectRoot);
    return appliedHash === desiredHash;
  } catch {
    return false;
  }
}

export class SnmpHostAgent {
  private readonly instanceId: string;
  private readonly intervalMs: number;
  private readonly publishedPort: number;
  private readonly projectRoot: string;
  private readonly baseFile: string;
  private readonly overrideFile: string;
  private lastAppliedFingerprint: string | undefined;
  private refreshPromise: Promise<void> | undefined;

  constructor(private readonly prisma: PrismaClient) {
    const configuredInstanceId = process.env.SNMP_HOST_INSTANCE_ID?.trim();
    this.instanceId = configuredInstanceId?.startsWith('host:') ? configuredInstanceId : `host:${configuredInstanceId || hostname()}`;
    this.intervalMs = positiveInteger(process.env.SNMP_HOST_AGENT_INTERVAL_SECONDS, 30, 'SNMP_HOST_AGENT_INTERVAL_SECONDS') * 1000;
    this.publishedPort = positiveInteger(process.env.SNMP_TRAP_HOST_PORT, 162, 'SNMP_TRAP_HOST_PORT');
    this.projectRoot = resolve(__dirname, '../../..');
    this.baseFile = resolve(this.projectRoot, 'docker-compose.yml');
    this.overrideFile = resolve(this.projectRoot, '.runtime/snmp-listeners.compose.yml');
  }

  get refreshSeconds() { return this.intervalMs / 1000; }

  async refresh() {
    if (this.refreshPromise) return this.refreshPromise;
    this.refreshPromise = this.performRefresh().finally(() => { this.refreshPromise = undefined; });
    return this.refreshPromise;
  }

  private async performRefresh() {
    const current = runtimeIpv4Interfaces(this.instanceId, networkInterfaces());
    if (!current.length) throw Object.assign(new Error('SNMP_HOST_INTERFACES_UNAVAILABLE'), { code: 'SNMP_HOST_INTERFACES_UNAVAILABLE' });
    const now = new Date();
    const existing = await this.prisma.snmpListenerInterface.findMany({ where: { instanceId: this.instanceId }, select: { id: true, name: true, address: true } });
    await this.prisma.$transaction([
      ...current.map((item) => this.prisma.snmpListenerInterface.upsert({
        where: { instanceId_name_address: { instanceId: item.instanceId, name: item.name, address: item.address } },
        create: { ...item, lastSeenAt: now },
        update: { internal: item.internal, lastSeenAt: now },
      })),
      this.prisma.snmpListenerInterface.deleteMany({ where: { id: { in: existing.filter((item) => !current.some((candidate) => candidate.name === item.name && candidate.address === item.address)).map((item) => item.id) } } }),
    ]);
    const config = await this.prisma.snmpListenerConfig.findUnique({ where: { id: 'default' }, select: { listenAll: true, selectedInterfaces: true } });
    const addresses = selectedHostAddresses(config, current);
    const contents = renderComposeOverride(addresses, this.publishedPort);
    const fingerprint = createHash('sha256').update(contents).digest('hex');
    if (fingerprint === this.lastAppliedFingerprint && await composeConfigurationIsApplied(this.projectRoot, this.baseFile, this.overrideFile)) return;
    await writeAtomic(this.overrideFile, contents);
    await runDockerCompose(this.projectRoot, this.baseFile, this.overrideFile);
    this.lastAppliedFingerprint = fingerprint;
    log('info', 'host listener bindings applied', { instanceId: this.instanceId, addresses, publishedPort: this.publishedPort });
  }
}

async function main() {
  if (process.env.SNMP_HOST_AGENT_DATABASE_URL) process.env.DATABASE_URL = process.env.SNMP_HOST_AGENT_DATABASE_URL;
  else if (process.env.SNMP_DATABASE_URL) process.env.DATABASE_URL = process.env.SNMP_DATABASE_URL;
  const prisma = new PrismaClient();
  const agent = new SnmpHostAgent(prisma);
  let stopping = false;
  let timer: NodeJS.Timeout | undefined;
  const stop = async () => {
    if (stopping) return;
    stopping = true;
    if (timer) clearInterval(timer);
    await prisma.$disconnect();
    process.exit(0);
  };
  process.once('SIGINT', () => void stop());
  process.once('SIGTERM', () => void stop());
  await agent.refresh();
  log('info', 'SNMP host agent started', { refreshSeconds: agent.refreshSeconds });
  timer = setInterval(() => void agent.refresh().catch((error) => log('error', 'host listener reconciliation failed', { errorCode: publicErrorCode(error) })), agent.refreshSeconds * 1000);
  await new Promise<void>(() => undefined);
}

if (require.main === module) {
  void main().catch((error) => {
    log('error', 'SNMP host agent startup failed', { errorCode: publicErrorCode(error) });
    process.exit(1);
  });
}
