ALTER TABLE "DiscoveryJob" ADD COLUMN "scannedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DiscoveryJob" ADD COLUMN "icmpReachableCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DiscoveryJob" ADD COLUMN "tcpReachableCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DiscoveryJob" ADD COLUMN "reachableCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DiscoveryJob" ADD COLUMN "unreachableCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DiscoveryJob" ADD COLUMN "resultCount" INTEGER NOT NULL DEFAULT 0;
