'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Check, ChevronRight, KeyRound, Play, RefreshCw, Search, Trash2, X } from 'lucide-react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { AppShell } from '@/components/layout/app-shell';
import { useAuth } from '@/lib/auth';
import { useSiteContext } from '@/lib/site-context';
import { listAllDevices, listDeviceModels } from '@/features/infrastructure/api';
import type { Device } from '@/features/infrastructure/types';
import {
  acceptSnmpPreRegistration, cancelSnmpPreRegistration, createDiscoveryJob, createSnmpPreRegistration,
  getDiscoveryDefaults, listDiscoveryJobs, listDiscoveryResults, listDiscoverySubnets, listSnmpPreRegistrations,
  reviewDiscoveryResult, rotateSnmpPreRegistration, type DiscoveryAcceptInput, type DiscoveryJob,
  type DiscoveryJobPayload, type DiscoveryResult, type SnmpPreRegistration, type SnmpPreRegistrationInput,
} from './api';

const emptyEnrollment: SnmpPreRegistrationInput = { sourceAddress: '', siteId: '', version: 'V3', username: '', community: '', authKey: '', privKey: '', authProtocol: 'SHA256', privProtocol: 'AES128', compatibilitySha1: false };

export default function DiscoveryPage() {
  const { hasRole } = useAuth(); const admin = hasRole('ADMIN'); const canEdit = admin || hasRole('NETWORK_OPERATOR'); const qc = useQueryClient();
  const { siteId } = useSiteContext();
  const [tab, setTab] = useState<'network' | 'snmp'>('network'); const [search, setSearch] = useState(''); const [selectedJob, setSelectedJob] = useState('');
  const [networkModal, setNetworkModal] = useState(false); const [enrollmentModal, setEnrollmentModal] = useState(false); const [candidate, setCandidate] = useState<SnmpPreRegistration | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [networkForm, setNetworkForm] = useState({ name: 'Discovery manual', subnetId: '', methods: ['ICMP', 'TCP'], tcpPorts: '22,80,443,3389' });
  const [enrollmentForm, setEnrollmentForm] = useState<SnmpPreRegistrationInput>(emptyEnrollment);
  const [acceptForm, setAcceptForm] = useState<DiscoveryAcceptInput>({ name: '', type: 'SWITCH', hostname: '', modelId: '' });

  useEffect(() => { const params = new URLSearchParams(location.search); setTab(params.get('tab') === 'snmp' ? 'snmp' : 'network'); if (params.get('action') === 'new') setNetworkModal(true); }, []);
  const { data: jobsData, refetch: refetchJobs } = useQuery({ queryKey: ['discovery', 'jobs'], queryFn: listDiscoveryJobs });
  const { data: defaults } = useQuery({ queryKey: ['discovery', 'defaults'], queryFn: getDiscoveryDefaults });
  const { data: subnetsData } = useQuery({ queryKey: ['discovery', 'subnets', siteId], queryFn: () => listDiscoverySubnets(siteId), enabled: Boolean(siteId) });
  const { data: results = [] } = useQuery({ queryKey: ['discovery', 'results', selectedJob], queryFn: () => listDiscoveryResults(selectedJob), enabled: Boolean(selectedJob) });
  const { data: enrollments = [], refetch: refetchEnrollments } = useQuery({ queryKey: ['discovery', 'snmp-enrollments', siteId], queryFn: async () => (await listSnmpPreRegistrations(siteId)).items, enabled: Boolean(siteId) && tab === 'snmp', refetchInterval: 15_000 });
  const { data: deviceData, refetch: refetchDevices } = useQuery({ queryKey: ['discovery', 'snmp-devices', siteId], queryFn: () => listAllDevices(siteId, ''), enabled: Boolean(siteId) && tab === 'snmp' });
  const { data: models = [] } = useQuery({ queryKey: ['infrastructure', 'device-models'], queryFn: listDeviceModels, enabled: Boolean(candidate) });
  const jobs = useMemo(() => jobsData?.items ?? [], [jobsData?.items]);
  const subnets = useMemo(() => subnetsData?.items ?? [], [subnetsData?.items]);
  useEffect(() => { if (defaults) setNetworkForm((value) => ({ ...value, methods: defaults.methods, tcpPorts: defaults.tcpPorts.join(',') })); }, [defaults]);
  useEffect(() => { if (subnets[0] && !networkForm.subnetId) setNetworkForm((value) => ({ ...value, subnetId: subnets[0].id })); }, [subnets, networkForm.subnetId]);

  const normalized = search.trim().toLowerCase();
  const visibleJobs = useMemo(() => normalized ? jobs.filter((job) => `${job.name} ${job.status} ${job.subnet.cidr} ${job.subnet.site?.name ?? ''}`.toLowerCase().includes(normalized)) : jobs, [jobs, normalized]);
  const visibleEnrollments = useMemo(() => normalized ? enrollments.filter((item) => `${item.sourceAddress} ${item.version} ${item.username ?? ''} ${item.status} ${item.latestTrapOid ?? ''}`.toLowerCase().includes(normalized)) : enrollments, [enrollments, normalized]);
  const snmpDevices = useMemo(() => (deviceData?.items ?? []).filter((item) => ['SWITCH', 'ROUTER', 'FIREWALL'].includes(item.type)).filter((item) => !normalized || `${item.name} ${item.hostname ?? ''} ${item.managementIp ?? ''} ${item.type}`.toLowerCase().includes(normalized)), [deviceData?.items, normalized]);
  const waiting = visibleEnrollments.filter((item) => item.status === 'WAITING'); const discovered = visibleEnrollments.filter((item) => item.status === 'DISCOVERED');

  const switchTab = (next: 'network' | 'snmp') => { setTab(next); setSearch(''); const url = new URL(location.href); url.searchParams.set('tab', next); history.replaceState({}, '', `${url.pathname}${url.search}`); };
  const refresh = async () => { setBusy(true); try { if (tab === 'snmp') await Promise.all([refetchEnrollments(), refetchDevices()]); else await refetchJobs(); } finally { setBusy(false); } };
  const createNetwork = async (event: FormEvent) => { event.preventDefault(); try { const payload: DiscoveryJobPayload = { name: networkForm.name, subnetId: networkForm.subnetId, methods: networkForm.methods, tcpPorts: networkForm.tcpPorts.split(',').map(Number).filter(Boolean) }; await createDiscoveryJob(payload); setNetworkModal(false); await refetchJobs(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível criar a descoberta.'); } };
  const review = async (id: string, status: 'APPROVED' | 'IGNORED') => { try { await reviewDiscoveryResult(id, status); qc.setQueryData<DiscoveryResult[]>(['discovery', 'results', selectedJob], (items = []) => items.map((item) => item.id === id ? { ...item, status } : item)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível rever o resultado.'); } };
  const saveEnrollment = async (event: FormEvent) => { event.preventDefault(); try { await createSnmpPreRegistration({ ...enrollmentForm, siteId }); setEnrollmentModal(false); setEnrollmentForm({ ...emptyEnrollment }); await refetchEnrollments(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível criar o pré-registo.'); } };
  const renew = async (id: string) => { try { await rotateSnmpPreRegistration(id); await refetchEnrollments(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível renovar o pré-registo.'); } };
  const cancel = async (id: string) => { if (!confirm('Cancelar este pré-registo SNMP? A credencial será removida.')) return; try { await cancelSnmpPreRegistration(id); await refetchEnrollments(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível cancelar o pré-registo.'); } };
  const openCandidate = (item: SnmpPreRegistration) => { setCandidate(item); setAcceptForm({ name: '', type: 'SWITCH', hostname: '', modelId: '' }); };
  const accept = async (event: FormEvent) => { event.preventDefault(); if (!candidate || !acceptForm.name.trim()) return; try { const device = await acceptSnmpPreRegistration(candidate.id, { ...acceptForm, name: acceptForm.name.trim(), hostname: acceptForm.hostname?.trim() || undefined, modelId: acceptForm.modelId || undefined, frontAssetId: undefined }); location.assign(`/infraestrutura?siteId=${encodeURIComponent(candidate.siteId)}&tab=devices&deviceId=${encodeURIComponent(device.id)}`); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível adicionar o equipamento.'); } };

  const actions = <><button className="topbar-action secondary-button" onClick={() => void refresh()}><RefreshCw size={14} className={busy ? 'spin' : ''} /> Atualizar</button>{tab === 'network' && canEdit && <button className="topbar-action primary-button" onClick={() => setNetworkModal(true)}><Play size={14} /> Nova descoberta</button>}{tab === 'snmp' && admin && <button className="topbar-action primary-button" onClick={() => { setEnrollmentForm({ ...emptyEnrollment, siteId }); setEnrollmentModal(true); }}><KeyRound size={14} /> Pré-registar IP</button>}</>;
  return <AppShell section="Descoberta" search={{ value: search, onChange: setSearch, placeholder: tab === 'snmp' ? 'Pesquisar IP, identidade ou trap…' : 'Pesquisar execuções…' }} actions={actions}><main className="module-page discovery-workspace">
    <header className="workspace-head"><div><span className="section-kicker">NETWORK DISCOVERY</span><h1>Descoberta</h1><p>Descoberta ativa de rede e onboarding passivo por traps SNMP.</p></div></header>
    <nav className="infra-menu" aria-label="Tipo de descoberta"><button className={tab === 'network' ? 'active' : ''} onClick={() => switchTab('network')}><Search size={15} /> Rede</button><button className={tab === 'snmp' ? 'active' : ''} onClick={() => switchTab('snmp')}><KeyRound size={15} /> SNMP</button></nav>
    {error && <div className="ipam-alert error"><X size={15} />{error}</div>}
    {tab === 'network' ? <NetworkDiscovery jobs={visibleJobs} allJobs={jobs} results={results} selectedJob={selectedJob} selectJob={setSelectedJob} canEdit={canEdit} review={review} searching={Boolean(normalized)} /> : <SnmpDiscovery devices={snmpDevices} siteId={siteId} waiting={waiting} discovered={discovered} admin={admin} canEdit={canEdit} renew={renew} cancel={cancel} accept={openCandidate} searching={Boolean(normalized)} />}
    {networkModal && <NetworkModal form={networkForm} setForm={setNetworkForm} subnets={subnets} close={() => setNetworkModal(false)} submit={createNetwork} />}
    {enrollmentModal && <EnrollmentModal form={enrollmentForm} setForm={setEnrollmentForm} close={() => setEnrollmentModal(false)} submit={saveEnrollment} />}
    {candidate && <AcceptModal candidate={candidate} form={acceptForm} setForm={setAcceptForm} models={models.filter((model) => model.type === acceptForm.type)} close={() => setCandidate(null)} submit={accept} />}
  </main></AppShell>;
}

function NetworkDiscovery({ jobs, allJobs, results, selectedJob, selectJob, canEdit, review, searching }: { jobs: DiscoveryJob[]; allJobs: DiscoveryJob[]; results: DiscoveryResult[]; selectedJob: string; selectJob: (id: string) => void; canEdit: boolean; review: (id: string, status: 'APPROVED' | 'IGNORED') => Promise<void>; searching: boolean }) {
  return <><div className="summary-stats"><div><strong>{allJobs.filter((item) => item.status === 'RUNNING').length}</strong><span>Em execução</span></div><div><strong>{allJobs.reduce((sum, item) => sum + item._count.results, 0)}</strong><span>Resultados</span></div><div><strong>{allJobs.reduce((sum, item) => sum + (item.unreachableCount ?? 0), 0)}</strong><span>Sem resposta</span></div></div><section className="ipam-card"><div className="panel-heading"><div><span className="section-kicker">HISTÓRICO</span><h2>Execuções recentes</h2></div></div>{jobs.map((job) => <button className="job-row" key={job.id} onClick={() => selectJob(job.id)}><span className={`job-status ${job.status.toLowerCase()}`} /><span><strong>{job.name}</strong><small>{job.subnet.cidr} · {job.subnet.site?.name ?? 'sem Site'} · {job._count.results} resultados · {job.status}</small></span><ChevronRight size={15} /></button>)}{!jobs.length && <div className="empty-context"><Search size={22} /><strong>{searching ? 'Sem execuções correspondentes' : 'Ainda não existem descobertas'}</strong></div>}</section>{selectedJob && <section className="ipam-card"><div className="panel-heading"><div><span className="section-kicker">REVISÃO MANUAL</span><h2>Resultados alcançáveis</h2></div></div>{results.map((result) => <div className="result-row" key={result.id}><span><strong>{result.address}</strong><small>{result.hostname || 'reverse DNS não encontrado'} · {result.icmpReachable ? `ICMP ${result.responseMs ?? ''}ms` : 'TCP alcançável'}{result.openPorts?.length ? ` · TCP ${result.openPorts.join(', ')}` : ''}</small></span>{result.status === 'PENDING' && canEdit ? <span className="result-actions"><button className="secondary-button" onClick={() => void review(result.id, 'APPROVED')}><Check size={13} /> Aprovar</button><button className="danger-button" onClick={() => void review(result.id, 'IGNORED')}><X size={13} /> Ignorar</button></span> : <em>{result.status}</em>}</div>)}{!results.length && <div className="no-data">Não existem resultados alcançáveis para esta execução.</div>}</section>}</>;
}

function SnmpDiscovery({ devices, siteId, waiting, discovered, admin, canEdit, renew, cancel, accept, searching }: { devices: Device[]; siteId: string; waiting: SnmpPreRegistration[]; discovered: SnmpPreRegistration[]; admin: boolean; canEdit: boolean; renew: (id: string) => Promise<void>; cancel: (id: string) => Promise<void>; accept: (item: SnmpPreRegistration) => void; searching: boolean }) {
  const totalTraps = discovered.reduce((sum, item) => sum + item.trapCount, 0); return <><div className="summary-stats"><div><strong>{devices.length}</strong><span>Equipamentos registados</span></div><div><strong>{waiting.length}</strong><span>A aguardar trap</span></div><div><strong>{discovered.length}</strong><span>Hosts descobertos · {totalTraps} traps</span></div></div><section className="ipam-card"><div className="panel-heading"><div><span className="section-kicker">INFRAESTRUTURA DO SITE</span><h2>Equipamentos disponíveis para SNMP</h2><p className="panel-description">Switches, routers e firewalls já registados podem receber configuração SNMP sem novo onboarding.</p></div></div>{devices.map((device) => <div className="result-row" key={device.id}><span><strong>{device.name}</strong><small>{device.type} · {device.managementIp || 'sem IP de gestão'}{device.hostname ? ` · ${device.hostname}` : ''}</small></span>{admin && <button className="secondary-button" disabled={!device.managementIp} onClick={() => location.assign(`/snmp?siteId=${encodeURIComponent(siteId)}&deviceId=${encodeURIComponent(device.id)}`)}><KeyRound size={13} /> Configurar SNMP</button>}</div>)}{!devices.length && <div className="no-data">{searching ? 'Sem equipamentos correspondentes.' : 'Ainda não existem switches, routers ou firewalls neste Site.'}</div>}</section><EnrollmentSection title="A aguardar traps" kicker="PRÉ-REGISTOS ATIVOS" items={waiting} empty={searching ? 'Sem pré-registos correspondentes.' : 'Ainda não existem IPs a aguardar traps.'} admin={admin} canEdit={false} renew={renew} cancel={cancel} accept={accept} /><EnrollmentSection title="Hosts descobertos" kicker="REVISÃO MANUAL" items={discovered} empty={searching ? 'Sem candidatos correspondentes.' : 'Nenhum equipamento pré-registado enviou traps.'} admin={admin} canEdit={canEdit} renew={renew} cancel={cancel} accept={accept} /></>;
}

function EnrollmentSection({ title, kicker, items, empty, admin, canEdit, renew, cancel, accept }: { title: string; kicker: string; items: SnmpPreRegistration[]; empty: string; admin: boolean; canEdit: boolean; renew: (id: string) => Promise<void>; cancel: (id: string) => Promise<void>; accept: (item: SnmpPreRegistration) => void }) {
  return <section className="ipam-card"><div className="panel-heading"><div><span className="section-kicker">{kicker}</span><h2>{title}</h2></div></div>{items.map((item) => <div className="result-row" key={item.id}><span><strong>{item.sourceAddress}</strong><small>{item.version}{item.username ? ` · ${item.username}` : ''} · {item.trapCount} traps{item.latestTrapOid ? ` · ${item.latestTrapOid}` : ''} · expira {new Date(item.expiresAt).toLocaleString('pt-PT')}</small></span><span className="result-actions">{canEdit && <button className="primary-button" onClick={() => accept(item)}><Check size={13} /> Adicionar equipamento</button>}{admin && <button className="secondary-button" onClick={() => void renew(item.id)}><RefreshCw size={13} /> Renovar</button>}{admin && <button className="danger-button" aria-label="Cancelar pré-registo" onClick={() => void cancel(item.id)}><Trash2 size={13} /></button>}</span></div>)}{!items.length && <div className="no-data">{empty}</div>}</section>;
}

function NetworkModal({ form, setForm, subnets, close, submit }: { form: { name: string; subnetId: string; methods: string[]; tcpPorts: string }; setForm: (value: typeof form) => void; subnets: Array<{ id: string; cidr: string }>; close: () => void; submit: (event: FormEvent) => Promise<void> }) {
  const toggle = (method: string) => setForm({ ...form, methods: form.methods.includes(method) ? form.methods.filter((item) => item !== method) : [...form.methods, method] }); return <div className="modal-backdrop"><section className="modal-card" role="dialog" aria-modal="true"><div className="modal-heading"><h2>Executar discovery</h2><button className="icon-button subtle" onClick={close} aria-label="Fechar"><X size={16} /></button></div><form className="modal-form" onSubmit={submit}><label>Nome<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Subnet<select required value={form.subnetId} onChange={(event) => setForm({ ...form, subnetId: event.target.value })}><option value="">Seleciona uma subnet</option>{subnets.map((subnet) => <option key={subnet.id} value={subnet.id}>{subnet.cidr}</option>)}</select></label><div className="method-checks">{['ICMP', 'TCP'].map((method) => <button key={method} type="button" className={form.methods.includes(method) ? 'method active' : 'method'} onClick={() => toggle(method)}>{method}</button>)}</div>{form.methods.includes('TCP') && <label>Portas TCP<input value={form.tcpPorts} onChange={(event) => setForm({ ...form, tcpPorts: event.target.value })} /></label>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={!form.methods.length || !form.subnetId}>Executar</button></div></form></section></div>;
}

function EnrollmentModal({ form, setForm, close, submit }: { form: SnmpPreRegistrationInput; setForm: (value: SnmpPreRegistrationInput) => void; close: () => void; submit: (event: FormEvent) => Promise<void> }) {
  return <div className="modal-backdrop"><section className="modal-card" role="dialog" aria-modal="true"><div className="modal-heading"><div><span className="section-kicker">VÁLIDO DURANTE 24 HORAS</span><h2>Pré-registar equipamento SNMP</h2></div><button className="icon-button subtle" onClick={close} aria-label="Fechar"><X size={16} /></button></div><form className="modal-form" onSubmit={submit}><label>IP esperado<input required inputMode="decimal" value={form.sourceAddress} onChange={(event) => setForm({ ...form, sourceAddress: event.target.value })} placeholder="192.0.2.10" /></label><label>Versão<select value={form.version} onChange={(event) => setForm({ ...form, version: event.target.value as 'V2C' | 'V3' })}><option value="V3">SNMPv3 authPriv</option><option value="V2C">SNMPv2c</option></select></label>{form.version === 'V2C' ? <label>Comunidade TRAP<input required minLength={8} type="password" autoComplete="new-password" value={form.community ?? ''} onChange={(event) => setForm({ ...form, community: event.target.value })} /></label> : <><label>Username<input required value={form.username ?? ''} onChange={(event) => setForm({ ...form, username: event.target.value })} /></label><div className="form-row"><label>Protocolo auth<select value={form.authProtocol ?? 'SHA256'} onChange={(event) => setForm({ ...form, authProtocol: event.target.value, compatibilitySha1: event.target.value === 'SHA1' })}><option>SHA256</option><option>SHA384</option><option>SHA512</option><option>SHA1</option></select></label><label>Privacidade<select value={form.privProtocol ?? 'AES128'} onChange={(event) => setForm({ ...form, privProtocol: event.target.value })}><option>AES128</option><option>AES256</option></select></label></div><label>Auth key<input required minLength={8} type="password" autoComplete="new-password" value={form.authKey ?? ''} onChange={(event) => setForm({ ...form, authKey: event.target.value })} /></label><label>Privacy key<input required minLength={8} type="password" autoComplete="new-password" value={form.privKey ?? ''} onChange={(event) => setForm({ ...form, privKey: event.target.value })} /></label></>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button"><KeyRound size={14} /> Autorizar IP</button></div></form></section></div>;
}

function AcceptModal({ candidate, form, setForm, models, close, submit }: { candidate: SnmpPreRegistration; form: DiscoveryAcceptInput; setForm: (value: DiscoveryAcceptInput) => void; models: Array<{ id: string; manufacturer: string; model: string }>; close: () => void; submit: (event: FormEvent) => Promise<void> }) {
  return <div className="modal-backdrop"><section className="modal-card" role="dialog" aria-modal="true"><div className="modal-heading"><div><span className="section-kicker">{candidate.site?.name ?? 'SITE'} · {candidate.sourceAddress}</span><h2>Adicionar equipamento descoberto</h2></div><button className="icon-button subtle" onClick={close} aria-label="Fechar"><X size={16} /></button></div><form className="modal-form" onSubmit={submit} autoComplete="off"><label>Nome do equipamento<input required autoFocus autoComplete="off" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Ex.: Switch principal" /></label><label>Hostname (opcional)<input autoComplete="off" value={form.hostname ?? ''} onChange={(event) => setForm({ ...form, hostname: event.target.value })} placeholder="Ex.: sw-core-01" /></label><label>Tipo<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value, modelId: '' })}><option>SWITCH</option><option>ROUTER</option><option>FIREWALL</option></select></label><label>Modelo (opcional)<select value={form.modelId ?? ''} onChange={(event) => setForm({ ...form, modelId: event.target.value })}><option value="">Sem modelo — usar ícone genérico</option>{models.map((model) => <option key={model.id} value={model.id}>{model.manufacturer} {model.model}</option>)}</select></label><p className="form-help">O equipamento será criado por localizar. O IP e a credencial TRAP serão associados automaticamente.</p><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={!form.name.trim()}><Check size={14} /> Adicionar equipamento</button></div></form></section></div>;
}
