'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Edit3, MapPin, Plus, RefreshCw, Search, ShieldCheck, Trash2, Users, X } from 'lucide-react';
import { AppShell } from '@/components/layout/app-shell';
import { AccessGroupsSettings } from './components/access-groups-settings';
import { useToast } from '@/components/ui/toast';
import { useAuth } from '@/lib/auth';
import { AppLocale, useI18n } from '@/lib/i18n';

const applicationRoles = ['ADMIN', 'NETWORK_OPERATOR', 'SYSTEMS_OPERATOR', 'AUDITOR', 'READ_ONLY'] as const;
type ApplicationRole = typeof applicationRoles[number];
type Site = { id: string; name: string; code: string; address?: string | null; city?: string | null; region?: string | null; country?: string | null; _count: { buildings: number; devices: number; vlans: number; subnets: number } };
type Organization = { settings: { organizationName?: string | null; organizationCode?: string | null; timezone: string; locale: AppLocale; setupCompleted: boolean }; sites: Site[] };
type DiscoveryDefaults = { methods: string[]; tcpPorts: number[]; reverseDns: boolean; intervalHours: number; allowedCidrs: string[] };
type AuditPolicy = { retentionDays: number; totalEvents: number; oldestEventAt?: string | null; lastCleanupAt?: string | null; lastCleanupDeletedCount?: number | null; nextCleanupAt?: string | null };
type ManagedUser = { externalId: string; username: string; displayName: string; email?: string | null; enabled: boolean; directRoles: ApplicationRole[]; inheritedRoles: ApplicationRole[]; effectiveRoles: ApplicationRole[]; pendingRoleRequest?: { id: string; requestedRoles: ApplicationRole[]; status: 'PENDING' | 'PROCESSING'; createdAt: string } | null };
type UserResult = { items: ManagedUser[]; page: number; pageSize: number; total: number; totalPages: number };
type Tab = 'organization' | 'sites' | 'groups' | 'users' | 'discovery' | 'audit';
type SiteForm = { id: string; name: string; code: string; address: string; city: string; region: string; country: string };
const emptySite: SiteForm = { id: '', name: '', code: '', address: '', city: '', region: '', country: 'Portugal' };

function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) { return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && close()}><section className="modal-card" role="dialog" aria-modal="true"><div className="modal-heading"><h2>{title}</h2><button className="icon-button subtle" onClick={close} aria-label="Fechar"><X size={16}/></button></div>{children}</section></div>; }

export default function SettingsPage() {
  const { apiFetch, hasRole, logout } = useAuth(); const { success, error: toastError } = useToast(); const { t, locale, setLocale, formatDate } = useI18n();
  const admin = hasRole('ADMIN'); const auditor = hasRole('AUDITOR');
  const tabs = useMemo<[Tab, string][]>(() => admin ? [['organization', t('settings.organization')], ['sites', t('settings.sites')], ['groups', 'Grupos'], ['users', t('settings.users')], ['discovery', t('settings.discovery')], ['audit', t('settings.audit')]] : auditor ? [['audit', t('settings.audit')]] : [], [admin, auditor, t, locale]);
  const [tab, setTab] = useState<Tab>('organization'); const [org, setOrg] = useState<Organization | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [orgForm, setOrgForm] = useState({ name: '', code: '', timezone: 'Europe/Lisbon', locale: 'pt-PT' as AppLocale });
  const [discovery, setDiscovery] = useState<DiscoveryDefaults>({ methods: ['ICMP', 'TCP'], tcpPorts: [22, 80, 443, 3389], reverseDns: true, intervalHours: 12, allowedCidrs: ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16', 'fc00::/7'] }); const [ports, setPorts] = useState('22, 80, 443, 3389'); const [allowedCidrs, setAllowedCidrs] = useState('10.0.0.0/8\n172.16.0.0/12\n192.168.0.0/16\nfc00::/7');
  const [audit, setAudit] = useState<AuditPolicy | null>(null); const [siteModal, setSiteModal] = useState(false); const [siteForm, setSiteForm] = useState<SiteForm>(emptySite); const [deleteSite, setDeleteSite] = useState<Site | null>(null); const [deleteCode, setDeleteCode] = useState('');
  const [users, setUsers] = useState<UserResult>({ items: [], page: 1, pageSize: 20, total: 0, totalPages: 1 }); const [userSearch, setUserSearch] = useState(''); const [usersLoading, setUsersLoading] = useState(false); const [editingUser, setEditingUser] = useState<ManagedUser | null>(null); const [roleDraft, setRoleDraft] = useState<ApplicationRole[]>([]);
  const [settingsQuery, setSettingsQuery] = useState('');
  const settingIndex = useMemo(() => [
    { tab: 'organization' as Tab, label: t('settings.name'), group: t('settings.organization'), keywords: 'nome name organização organization' },
    { tab: 'organization' as Tab, label: t('settings.code'), group: t('settings.organization'), keywords: 'código code organização organization' },
    { tab: 'organization' as Tab, label: t('settings.timezone'), group: t('settings.organization'), keywords: 'fuso horário timezone' },
    { tab: 'organization' as Tab, label: t('settings.language'), group: t('settings.organization'), keywords: 'linguagem idioma language locale português english' },
    { tab: 'sites' as Tab, label: t('settings.sitesTitle'), group: t('settings.sites'), keywords: 'sites localização location edifícios buildings equipamentos devices vlan subnet' },
    ...(admin ? [{ tab: 'groups' as Tab, label: 'Grupos de acesso', group: 'Grupos', keywords: 'grupos groups membros permissões ipam infraestrutura' }, { tab: 'users' as Tab, label: t('settings.usersTitle'), group: t('settings.users'), keywords: 'utilizadores users roles permissões keycloak acessos' }] : []),
    { tab: 'discovery' as Tab, label: t('settings.methods'), group: t('settings.discovery'), keywords: 'discovery métodos methods icmp tcp' },
    { tab: 'discovery' as Tab, label: t('settings.ports'), group: t('settings.discovery'), keywords: 'discovery portas ports tcp' },
    { tab: 'discovery' as Tab, label: t('settings.reverseDns'), group: t('settings.discovery'), keywords: 'discovery dns reverse hostname nomes' },
    { tab: 'discovery' as Tab, label: t('settings.interval'), group: t('settings.discovery'), keywords: 'discovery intervalo interval schedule periodicidade' },
    ...((admin || auditor) ? [{ tab: 'audit' as Tab, label: t('settings.retention'), group: t('settings.audit'), keywords: 'auditoria audit retenção retention dias limpeza eventos' }] : []),
  ], [admin, auditor, locale, t]);
  const settingMatches = useMemo(() => { const query = settingsQuery.trim().toLocaleLowerCase(locale); if (!query) return []; return settingIndex.filter((item) => `${item.label} ${item.group} ${item.keywords}`.toLocaleLowerCase(locale).includes(query)).slice(0, 8); }, [locale, settingIndex, settingsQuery]);

  const loadCore = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const requests: Promise<unknown>[] = [apiFetch<Organization>('/api/v1/settings/organization'), apiFetch<DiscoveryDefaults>('/api/v1/settings/discovery')]; if (admin || auditor) requests.push(apiFetch<AuditPolicy>('/api/v1/settings/audit-policy'));
      const [organization, defaults, auditResult] = await Promise.all(requests) as [Organization, DiscoveryDefaults, AuditPolicy?]; setOrg(organization); setOrgForm({ name: organization.settings.organizationName ?? '', code: organization.settings.organizationCode ?? '', timezone: organization.settings.timezone, locale: organization.settings.locale ?? 'pt-PT' }); setDiscovery(defaults); setPorts(defaults.tcpPorts.join(', ')); setAllowedCidrs(defaults.allowedCidrs.join('\n')); if (auditResult) setAudit(auditResult);
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível carregar as definições.'); } finally { setLoading(false); }
  }, [admin, auditor, apiFetch]);
  const loadUsers = useCallback(async (page = 1, search = userSearch) => { if (!admin) return; setUsersLoading(true); setError(''); try { setUsers(await apiFetch<UserResult>(`/api/v1/settings/users?${new URLSearchParams({ page: String(page), pageSize: '20', ...(search.trim() ? { search: search.trim() } : {}) })}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : t('settings.kcUnavailable')); } finally { setUsersLoading(false); } }, [admin, apiFetch, t, userSearch]);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get('tab'); const normalized: Tab = requested === 'session' ? 'users' : ['organization', 'sites', 'groups', 'users', 'discovery', 'audit'].includes(requested ?? '') ? requested as Tab : 'organization'; setTab(admin ? normalized : auditor ? 'audit' : 'organization'); void loadCore(); }, [admin, auditor, loadCore]);
  useEffect(() => { if (tab !== 'users' || !admin) return; const timer = window.setTimeout(() => void loadUsers(1, userSearch), 250); return () => window.clearTimeout(timer); }, [admin, loadUsers, tab, userSearch]);
  const changeTab = (next: Tab) => { setTab(next); const query = new URLSearchParams(window.location.search); query.set('tab', next); window.history.replaceState({}, '', `/definicoes?${query}`); setError(''); };
  const roleLabel = (role: ApplicationRole) => t(`role.${role}`, role);
  const requestedRoleLabels = (roles: ApplicationRole[]) => roles.map(roleLabel).join(locale === 'pt-PT' ? ' e ' : ' and ');
  const saveOrganization = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await apiFetch('/api/v1/settings/organization', { method: 'PATCH', body: JSON.stringify(orgForm) }); setLocale(orgForm.locale); success(t('settings.organization'), t('common.save')); await loadCore(); } catch (reason) { const message = reason instanceof Error ? reason.message : 'Não foi possível guardar.'; setError(message); toastError(t('settings.organization'), message); } finally { setSaving(false); } };
  const saveDiscovery = async (event: FormEvent) => { event.preventDefault(); const tcpPorts = [...new Set(ports.split(',').map((value) => Number(value.trim())).filter((value) => Number.isInteger(value) && value > 0 && value <= 65535))]; const cidrs = [...new Set(allowedCidrs.split(/[\n,]/).map((value) => value.trim()).filter(Boolean))]; setSaving(true); try { const result = await apiFetch<DiscoveryDefaults>('/api/v1/settings/discovery', { method: 'PATCH', body: JSON.stringify({ ...discovery, tcpPorts, allowedCidrs: cidrs }) }); setDiscovery(result); setPorts(result.tcpPorts.join(', ')); setAllowedCidrs(result.allowedCidrs.join('\n')); success(t('settings.discovery'), t('common.save')); } catch (reason) { const message = reason instanceof Error ? reason.message : 'Não foi possível guardar.'; setError(message); toastError(t('settings.discovery'), message); } finally { setSaving(false); } };
  const saveAudit = async (event: FormEvent) => { event.preventDefault(); if (!audit) return; setSaving(true); try { setAudit(await apiFetch<AuditPolicy>('/api/v1/settings/audit-policy', { method: 'PATCH', body: JSON.stringify({ retentionDays: audit.retentionDays }) })); success(t('settings.audit'), t('common.save')); } catch (reason) { const message = reason instanceof Error ? reason.message : 'Não foi possível guardar.'; setError(message); toastError(t('settings.audit'), message); } finally { setSaving(false); } };
  const openSite = (site?: Site) => { setSiteForm(site ? { id: site.id, name: site.name, code: site.code, address: site.address ?? '', city: site.city ?? '', region: site.region ?? '', country: site.country ?? '' } : emptySite); setSiteModal(true); };
  const saveSite = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const { id, ...body } = siteForm; await apiFetch(id ? `/api/v1/sites/${id}` : '/api/v1/sites', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(body) }); setSiteModal(false); success(t('settings.sites'), t('common.save')); await loadCore(); } catch (reason) { const message = reason instanceof Error ? reason.message : 'Não foi possível guardar o Site.'; setError(message); toastError(t('settings.sites'), message); } finally { setSaving(false); } };
  const confirmDeleteSite = async () => { if (!deleteSite || deleteCode.trim().toUpperCase() !== deleteSite.code.toUpperCase()) return; setSaving(true); try { await apiFetch(`/api/v1/sites/${deleteSite.id}`, { method: 'DELETE' }); setDeleteSite(null); setDeleteCode(''); success(t('settings.sites'), t('common.delete')); await loadCore(); } catch (reason) { const message = reason instanceof Error ? reason.message : t('settings.emptyOnly'); setError(message); toastError(t('settings.sites'), message); } finally { setSaving(false); } };
  const saveRoles = async () => { if (!editingUser) return; setSaving(true); try { const result = await apiFetch<{ reauthenticationRequired: boolean }>(`/api/v1/settings/users/${editingUser.externalId}/roles`, { method: 'PATCH', body: JSON.stringify({ roles: roleDraft }) }); setEditingUser(null); success(t('settings.users'), t('common.save')); if (result.reauthenticationRequired) { await logout(); return; } await loadUsers(users.page); } catch (reason) { const message = reason instanceof Error ? reason.message : 'Não foi possível atualizar as roles.'; setError(message); toastError(t('settings.users'), message); } finally { setSaving(false); } };
  const decideRoleRequest = async (item: ManagedUser, decision: 'APPROVE' | 'REJECT') => { const request = item.pendingRoleRequest; if (!request || (request.status !== 'PENDING' && !(request.status === 'PROCESSING' && decision === 'APPROVE'))) return; setSaving(true); try { await apiFetch(`/api/v1/settings/role-requests/${request.id}`, { method: 'PATCH', body: JSON.stringify({ decision }) }); success(t('settings.users'), t(decision === 'APPROVE' ? 'settings.requestApproved' : 'settings.requestRejected')); await loadUsers(users.page); } catch (reason) { const message = reason instanceof Error ? reason.message : t('settings.requestDecisionError'); setError(message); toastError(t('settings.users'), message); } finally { setSaving(false); } };

  return <AppShell section={t('settings.title')} search={{ value: settingsQuery, onChange: setSettingsQuery, placeholder: t('settings.searchPlaceholder') }} actions={<button className="topbar-action secondary-button" onClick={() => void loadCore()}><RefreshCw size={14}/>{t('common.refresh')}</button>}><main className="settings-workspace"><header className="workspace-head"><div><span className="section-kicker">{t('settings.kicker')}</span><h1>{t('settings.title')}</h1></div></header>{error && <div className="ipam-alert error"><X size={15}/>{error}</div>}{settingsQuery.trim() && <section className="settings-quick-results" aria-label={t('settings.searchResults')}>{settingMatches.length ? settingMatches.map((item) => <button key={`${item.tab}-${item.label}`} onClick={() => { changeTab(item.tab); setSettingsQuery(''); }}><Search size={14}/><span><strong>{item.label}</strong><small>{item.group}</small></span><ChevronRight size={14}/></button>) : <div className="settings-search-empty">{t('settings.noResults', 'Sem definições correspondentes.')}</div>}</section>}<nav className="settings-tabs" aria-label={t('settings.title')}>{tabs.map(([value, label]) => <button className={tab === value ? 'active' : ''} key={value} onClick={() => changeTab(value)}>{label}</button>)}</nav>
    {loading ? <section className="ipam-card settings-panel empty-context"><RefreshCw size={20} className="spin"/><span>{t('common.loading')}</span></section> : tab === 'organization' ? <section className="ipam-card settings-panel"><div className="panel-heading"><div><span className="section-kicker">{t('settings.organization').toUpperCase()}</span><h2>{t('settings.orgTitle')}</h2></div></div><form className="settings-form" onSubmit={saveOrganization}><label>{t('settings.name')}<input required disabled={!admin} value={orgForm.name} onChange={(event) => setOrgForm({ ...orgForm, name: event.target.value })}/></label><div className="form-row"><label>{t('settings.code')}<input required disabled={!admin} value={orgForm.code} onChange={(event) => setOrgForm({ ...orgForm, code: event.target.value })}/></label><label>{t('settings.timezone')}<select disabled={!admin} value={orgForm.timezone} onChange={(event) => setOrgForm({ ...orgForm, timezone: event.target.value })}>{['Europe/Lisbon', 'UTC', 'Europe/London', 'Europe/Madrid'].map((value) => <option key={value}>{value}</option>)}</select></label></div><label>{t('settings.language')}<select disabled={!admin} value={orgForm.locale} onChange={(event) => setOrgForm({ ...orgForm, locale: event.target.value as AppLocale })}><option value="pt-PT">{t('settings.pt')}</option><option value="en-US">{t('settings.en')}</option></select></label>{admin && <button className="primary-button" disabled={saving}><Check size={14}/>{t('common.save')}</button>}</form></section>
    : tab === 'sites' ? <section className="ipam-card settings-panel"><div className="panel-heading"><div><span className="section-kicker">{t('settings.sites').toUpperCase()}</span><h2>{t('settings.sitesTitle')}</h2></div>{admin && <button className="primary-button" onClick={() => openSite()}><Plus size={14}/>{t('settings.newSite')}</button>}</div><div className="settings-site-grid">{org?.sites.map((site) => <article className="settings-site-card" key={site.id}><div className="settings-site-head"><span className="settings-site-mark"><MapPin size={16}/></span><div><strong>{site.name}</strong><small>{site.code}</small></div>{admin && <div className="row-actions"><button title={t('common.edit')} onClick={() => openSite(site)}><Edit3 size={14}/></button><button title={t('common.delete')} onClick={() => { setDeleteSite(site); setDeleteCode(''); }}><Trash2 size={14}/></button></div>}</div><p>{[site.address, site.city, site.region, site.country].filter(Boolean).join(' · ') || '—'}</p><div className="settings-site-counts"><span><b>{site._count.buildings}</b> {t('settings.buildings')}</span><span><b>{site._count.devices}</b> {t('settings.equipment')}</span><span><b>{site._count.vlans}</b> VLANs</span><span><b>{site._count.subnets}</b> subnets</span></div></article>)}{!org?.sites.length && <div className="empty-context"><MapPin size={22}/><strong>{t('settings.noSites')}</strong></div>}</div></section>
    : tab === 'groups' ? <AccessGroupsSettings sites={org?.sites ?? []}/>
    : tab === 'users' ? <section className="ipam-card settings-panel"><div className="panel-heading"><div><span className="section-kicker">KEYCLOAK</span><h2>{t('settings.usersTitle')}</h2></div><button className="secondary-button" onClick={() => void loadUsers(users.page)}><RefreshCw size={14} className={usersLoading ? 'spin' : ''}/>{t('common.refresh')}</button></div><label className="settings-search"><Search size={15}/><input value={userSearch} onChange={(event) => setUserSearch(event.target.value)} placeholder={t('settings.searchUsers')}/></label><div className="settings-user-list">{users.items.map((item) => <article className="settings-user-row" key={item.externalId}><span className="user-status-icon"><Users size={15}/></span><span className="settings-user-identity"><strong>{item.displayName}</strong><small>{item.username}{item.email ? ` · ${item.email}` : ''}</small></span><div className="role-list">{item.directRoles.map((role) => <span className="state-badge" title={role} key={role}>{roleLabel(role)}</span>)}{item.inheritedRoles.map((role) => <span className="state-badge inherited" title={`${t('settings.inheritedRoles')} · ${role}`} key={`inherited-${role}`}>{roleLabel(role)} · ↳</span>)}</div>{item.pendingRoleRequest ? <div className="role-request-actions"><strong>{item.pendingRoleRequest.status === 'PROCESSING' ? t('settings.requestProcessing') : `${t('settings.requested')} ${requestedRoleLabels(item.pendingRoleRequest.requestedRoles)}`}</strong><div><button className="secondary-button" disabled={saving} aria-label={`${t(item.pendingRoleRequest.status === 'PROCESSING' ? 'settings.finish' : 'settings.accept')} · ${item.displayName}`} onClick={() => void decideRoleRequest(item, 'APPROVE')}><Check size={13}/>{t(item.pendingRoleRequest.status === 'PROCESSING' ? 'settings.finish' : 'settings.accept')}</button><button className="danger-button" disabled={saving || item.pendingRoleRequest.status === 'PROCESSING'} aria-label={`${t('settings.reject')} · ${item.displayName}`} onClick={() => void decideRoleRequest(item, 'REJECT')}><X size={13}/>{t('settings.reject')}</button></div></div> : <button className="secondary-button" onClick={() => { setEditingUser(item); setRoleDraft(item.directRoles); }}><Edit3 size={13}/>{t('common.edit')}</button>}</article>)}{!usersLoading && !users.items.length && <div className="empty-context"><Users size={22}/><strong>{t('settings.noUsers')}</strong></div>}</div><div className="settings-pagination"><span>{users.total} {t('settings.userCount')}</span><div><button disabled={users.page <= 1} onClick={() => void loadUsers(users.page - 1)}><ChevronLeft size={14}/></button><b>{users.page} / {users.totalPages}</b><button disabled={users.page >= users.totalPages} onClick={() => void loadUsers(users.page + 1)}><ChevronRight size={14}/></button></div></div></section>
    : tab === 'discovery' ? <section className="ipam-card settings-panel"><div className="panel-heading"><div><span className="section-kicker">DISCOVERY</span><h2>{t('settings.discoveryTitle')}</h2><p className="panel-description">{t('settings.newOnly')}</p></div></div><form className="settings-form" onSubmit={saveDiscovery}><fieldset disabled={!admin}><legend>{t('settings.methods')}</legend><div className="settings-methods">{['ICMP', 'TCP'].map((method) => <label key={method}><input type="checkbox" checked={discovery.methods.includes(method)} onChange={(event) => setDiscovery({ ...discovery, methods: event.target.checked ? [...discovery.methods, method] : discovery.methods.filter((item) => item !== method) })}/>{method}</label>)}</div></fieldset><div className="form-row"><label>{t('settings.ports')}<input disabled={!admin || !discovery.methods.includes('TCP')} value={ports} onChange={(event) => setPorts(event.target.value)} placeholder="22, 80, 443, 3389"/></label><label>{t('settings.interval')}<select disabled={!admin} value={discovery.intervalHours} onChange={(event) => setDiscovery({ ...discovery, intervalHours: Number(event.target.value) })}>{[6, 12, 24, 168].map((hours) => <option value={hours} key={hours}>{hours === 168 ? '7 dias' : `${hours}h`}</option>)}</select></label></div><label>{t('settings.allowedCidrs')}<textarea disabled={!admin} rows={5} value={allowedCidrs} onChange={(event) => setAllowedCidrs(event.target.value)} placeholder={'10.0.0.0/8\n192.168.0.0/16'}/><small>{t('settings.allowedCidrsHint')}</small></label><label className="settings-check"><input type="checkbox" disabled={!admin} checked={discovery.reverseDns} onChange={(event) => setDiscovery({ ...discovery, reverseDns: event.target.checked })}/>{t('settings.reverseDns')}</label>{admin && <button className="primary-button" disabled={saving || !discovery.methods.length}><Check size={14}/>{t('common.save')}</button>}</form></section>
    : <section className="ipam-card settings-panel"><div className="panel-heading"><div><span className="section-kicker">{t('settings.audit').toUpperCase()}</span><h2>{t('settings.auditTitle')}</h2></div></div>{audit && <><div className="detail-grid settings-audit-stats"><div><span>{t('settings.totalEvents')}</span><strong>{audit.totalEvents.toLocaleString(locale)}</strong></div><div><span>{t('settings.oldestEvent')}</span><strong>{formatDate(audit.oldestEventAt)}</strong></div><div><span>{t('settings.lastCleanup')}</span><strong>{formatDate(audit.lastCleanupAt)}</strong></div><div><span>{t('settings.nextCleanup')}</span><strong>{formatDate(audit.nextCleanupAt)}</strong></div></div><form className="settings-form compact" onSubmit={saveAudit}><label>{t('settings.retention')}<input type="number" min="1" max="3650" disabled={!admin} value={audit.retentionDays} onChange={(event) => setAudit({ ...audit, retentionDays: Number(event.target.value) })}/></label>{admin && <button className="primary-button" disabled={saving}><Check size={14}/>{t('common.save')}</button>}</form></>}</section>}
    {siteModal && <Modal title={siteForm.id ? t('common.edit') : t('settings.newSite')} close={() => setSiteModal(false)}><form className="modal-form" onSubmit={saveSite}><div className="form-row"><label>{t('settings.name')}<input required value={siteForm.name} onChange={(event) => setSiteForm({ ...siteForm, name: event.target.value })}/></label><label>{t('settings.code')}<input required value={siteForm.code} onChange={(event) => setSiteForm({ ...siteForm, code: event.target.value })}/></label></div><label>{t('settings.address')}<input value={siteForm.address} onChange={(event) => setSiteForm({ ...siteForm, address: event.target.value })}/></label><div className="form-row"><label>{t('settings.city')}<input value={siteForm.city} onChange={(event) => setSiteForm({ ...siteForm, city: event.target.value })}/></label><label>{t('settings.region')}<input value={siteForm.region} onChange={(event) => setSiteForm({ ...siteForm, region: event.target.value })}/></label></div><label>{t('settings.country')}<input value={siteForm.country} onChange={(event) => setSiteForm({ ...siteForm, country: event.target.value })}/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setSiteModal(false)}>{t('common.cancel')}</button><button className="primary-button" disabled={saving}><Check size={14}/>{t('common.save')}</button></div></form></Modal>}
    {deleteSite && <Modal title={`${t('common.delete')} ${deleteSite.name}`} close={() => setDeleteSite(null)}><div className="modal-form"><p>{t('settings.emptyOnly')}</p><label>{t('settings.confirmCode')} <strong>{deleteSite.code}</strong><input autoFocus value={deleteCode} onChange={(event) => setDeleteCode(event.target.value)}/></label><div className="modal-actions"><button className="secondary-button" onClick={() => setDeleteSite(null)}>{t('common.cancel')}</button><button className="danger-button" disabled={saving || deleteCode.trim().toUpperCase() !== deleteSite.code.toUpperCase()} onClick={() => void confirmDeleteSite()}><Trash2 size={14}/>{t('common.delete')}</button></div></div></Modal>}
    {editingUser && <Modal title={editingUser.displayName} close={() => setEditingUser(null)}><div className="modal-form"><span className="section-kicker">{t('settings.directRoles')}</span><div className="settings-role-picker">{applicationRoles.map((role) => <label key={role}><input type="checkbox" checked={roleDraft.includes(role)} onChange={(event) => setRoleDraft(event.target.checked ? [...roleDraft, role] : roleDraft.filter((item) => item !== role))}/><strong>{roleLabel(role)}</strong></label>)}</div>{editingUser.inheritedRoles.length > 0 && <div><span className="section-kicker">{t('settings.inheritedRoles')}</span><div className="role-list">{editingUser.inheritedRoles.map((role) => <span className="state-badge inherited" key={role}>{roleLabel(role)}</span>)}</div></div>}<div className="modal-actions"><button className="secondary-button" onClick={() => setEditingUser(null)}>{t('common.cancel')}</button><button className="primary-button" disabled={saving || !new Set([...roleDraft, ...editingUser.inheritedRoles]).size} onClick={() => void saveRoles()}><ShieldCheck size={14}/>{t('common.save')}</button></div></div></Modal>}
  </main></AppShell>;
}
